package defpackage;

/* JADX INFO: loaded from: classes.dex */
public final class ag {
    public int b;
    public int c;
    int d;
    boolean a = false;
    public int e = -1;
    public int f = -1;
    public float g = -1.0f;
    public int h = -1;
    public int i = -1;
    public int j = -1;
    public int k = -1;
    public int l = -1;
    public int m = -1;
    public int n = -1;
    public int o = -1;
    public int p = -1;
    public int q = -1;
    public int r = -1;
    public int s = -1;
    public int t = -1;
    public float u = 0.5f;
    public float v = 0.5f;
    public String w = null;
    public int x = -1;
    public int y = -1;
    public int z = -1;
    public int A = -1;
    public int B = -1;
    public int C = -1;
    public int D = -1;
    public int E = -1;
    public int F = -1;
    public int G = 0;
    public int H = -1;
    public int I = -1;
    public int J = -1;
    public int K = -1;
    public int L = -1;
    public int M = -1;
    public float N = 0.0f;
    public float O = 0.0f;
    public int P = 0;
    public int Q = 0;
    public float R = 1.0f;
    public boolean S = false;
    public float T = 0.0f;
    public float U = 0.0f;
    public float V = 0.0f;
    public float W = 1.0f;
    public float X = 1.0f;
    public float Y = 0.0f;
    public float Z = 0.0f;
    public float aa = 0.0f;
    public float ab = 0.0f;
    public float ac = 0.0f;
    public int ad = -1;
    public int ae = -1;
    public int af = -1;
    public int ag = -1;
    public int ah = -1;
    public int ai = -1;

    public final void a(af afVar) {
        afVar.d = this.h;
        afVar.e = this.i;
        afVar.f = this.j;
        afVar.g = this.k;
        afVar.h = this.l;
        afVar.i = this.m;
        afVar.j = this.n;
        afVar.k = this.o;
        afVar.l = this.p;
        afVar.m = this.q;
        afVar.n = this.r;
        afVar.o = this.s;
        afVar.p = this.t;
        afVar.leftMargin = this.A;
        afVar.rightMargin = this.B;
        afVar.topMargin = this.C;
        afVar.bottomMargin = this.D;
        afVar.u = this.M;
        afVar.v = this.L;
        afVar.w = this.u;
        afVar.x = this.v;
        afVar.y = this.w;
        afVar.K = this.x;
        afVar.L = this.y;
        afVar.B = this.N;
        afVar.A = this.O;
        afVar.D = this.Q;
        afVar.C = this.P;
        afVar.E = this.ad;
        afVar.F = this.ae;
        afVar.I = this.af;
        afVar.J = this.ag;
        afVar.G = this.ah;
        afVar.H = this.ai;
        afVar.M = this.z;
        afVar.c = this.g;
        afVar.a = this.e;
        afVar.b = this.f;
        afVar.width = this.b;
        afVar.height = this.c;
        afVar.setMarginStart(this.F);
        afVar.setMarginEnd(this.E);
        afVar.a();
    }

    public final /* bridge */ /* synthetic */ Object clone() {
        ag agVar = new ag();
        agVar.a = this.a;
        agVar.b = this.b;
        agVar.c = this.c;
        agVar.e = this.e;
        agVar.f = this.f;
        agVar.g = this.g;
        agVar.h = this.h;
        agVar.i = this.i;
        agVar.j = this.j;
        agVar.k = this.k;
        agVar.l = this.l;
        agVar.m = this.m;
        agVar.n = this.n;
        agVar.o = this.o;
        agVar.p = this.p;
        agVar.q = this.q;
        agVar.r = this.r;
        agVar.s = this.s;
        agVar.t = this.t;
        agVar.u = this.u;
        agVar.v = this.v;
        agVar.w = this.w;
        agVar.x = this.x;
        agVar.y = this.y;
        agVar.u = this.u;
        agVar.u = this.u;
        agVar.u = this.u;
        agVar.u = this.u;
        agVar.u = this.u;
        agVar.z = this.z;
        agVar.A = this.A;
        agVar.B = this.B;
        agVar.C = this.C;
        agVar.D = this.D;
        agVar.E = this.E;
        agVar.F = this.F;
        agVar.G = this.G;
        agVar.H = this.H;
        agVar.I = this.I;
        agVar.J = this.J;
        agVar.K = this.K;
        agVar.L = this.L;
        agVar.M = this.M;
        agVar.N = this.N;
        agVar.O = this.O;
        agVar.P = this.P;
        agVar.Q = this.Q;
        agVar.R = this.R;
        agVar.S = this.S;
        agVar.T = this.T;
        agVar.U = this.U;
        agVar.V = this.V;
        agVar.W = this.W;
        agVar.X = this.X;
        agVar.Y = this.Y;
        agVar.Z = this.Z;
        agVar.aa = this.aa;
        agVar.ab = this.ab;
        agVar.ac = this.ac;
        agVar.ad = this.ad;
        agVar.ae = this.ae;
        agVar.af = this.af;
        agVar.ag = this.ag;
        agVar.ah = this.ah;
        agVar.ai = this.ai;
        return agVar;
    }
}
