package defpackage;

import android.R;

/* JADX INFO: loaded from: classes.dex */
public final class alx {
    public static final int[] a = {R.attr.src, com.google.android.GoogleCameraEngR18F1.R.attr.background_border_cap, com.google.android.GoogleCameraEngR18F1.R.attr.background_border_color, com.google.android.GoogleCameraEngR18F1.R.attr.background_border_width, com.google.android.GoogleCameraEngR18F1.R.attr.background_color, com.google.android.GoogleCameraEngR18F1.R.attr.background_radius, com.google.android.GoogleCameraEngR18F1.R.attr.background_radius_percent, com.google.android.GoogleCameraEngR18F1.R.attr.background_radius_pressed, com.google.android.GoogleCameraEngR18F1.R.attr.background_radius_pressed_percent, com.google.android.GoogleCameraEngR18F1.R.attr.background_shadow_width, com.google.android.GoogleCameraEngR18F1.R.attr.circle_border_cap, com.google.android.GoogleCameraEngR18F1.R.attr.circle_border_color, com.google.android.GoogleCameraEngR18F1.R.attr.circle_border_width, com.google.android.GoogleCameraEngR18F1.R.attr.circle_color, com.google.android.GoogleCameraEngR18F1.R.attr.circle_padding, com.google.android.GoogleCameraEngR18F1.R.attr.circle_radius, com.google.android.GoogleCameraEngR18F1.R.attr.circle_radius_percent, com.google.android.GoogleCameraEngR18F1.R.attr.circle_radius_pressed, com.google.android.GoogleCameraEngR18F1.R.attr.circle_radius_pressed_percent, com.google.android.GoogleCameraEngR18F1.R.attr.clip_dimen, com.google.android.GoogleCameraEngR18F1.R.attr.image_circle_percentage, com.google.android.GoogleCameraEngR18F1.R.attr.image_horizontal_offcenter_percentage, com.google.android.GoogleCameraEngR18F1.R.attr.image_tint, com.google.android.GoogleCameraEngR18F1.R.attr.img_circle_percentage, com.google.android.GoogleCameraEngR18F1.R.attr.img_horizontal_offset_percentage, com.google.android.GoogleCameraEngR18F1.R.attr.img_padding, com.google.android.GoogleCameraEngR18F1.R.attr.img_tint, com.google.android.GoogleCameraEngR18F1.R.attr.shadow_width, com.google.android.GoogleCameraEngR18F1.R.attr.square_dimen};
    public static final int[] b = {com.google.android.GoogleCameraEngR18F1.R.attr.pageIndicatorDotColor, com.google.android.GoogleCameraEngR18F1.R.attr.pageIndicatorDotColorSelected, com.google.android.GoogleCameraEngR18F1.R.attr.pageIndicatorDotFadeInDuration, com.google.android.GoogleCameraEngR18F1.R.attr.pageIndicatorDotFadeOutDelay, com.google.android.GoogleCameraEngR18F1.R.attr.pageIndicatorDotFadeOutDuration, com.google.android.GoogleCameraEngR18F1.R.attr.pageIndicatorDotFadeWhenIdle, com.google.android.GoogleCameraEngR18F1.R.attr.pageIndicatorDotRadius, com.google.android.GoogleCameraEngR18F1.R.attr.pageIndicatorDotRadiusSelected, com.google.android.GoogleCameraEngR18F1.R.attr.pageIndicatorDotShadowColor, com.google.android.GoogleCameraEngR18F1.R.attr.pageIndicatorDotShadowDx, com.google.android.GoogleCameraEngR18F1.R.attr.pageIndicatorDotShadowDy, com.google.android.GoogleCameraEngR18F1.R.attr.pageIndicatorDotShadowRadius, com.google.android.GoogleCameraEngR18F1.R.attr.pageIndicatorDotSpacing, com.google.android.GoogleCameraEngR18F1.R.attr.wsPageIndicatorDotColor, com.google.android.GoogleCameraEngR18F1.R.attr.wsPageIndicatorDotColorSelected, com.google.android.GoogleCameraEngR18F1.R.attr.wsPageIndicatorDotFadeInDuration, com.google.android.GoogleCameraEngR18F1.R.attr.wsPageIndicatorDotFadeOutDelay, com.google.android.GoogleCameraEngR18F1.R.attr.wsPageIndicatorDotFadeOutDuration, com.google.android.GoogleCameraEngR18F1.R.attr.wsPageIndicatorDotFadeWhenIdle, com.google.android.GoogleCameraEngR18F1.R.attr.wsPageIndicatorDotRadius, com.google.android.GoogleCameraEngR18F1.R.attr.wsPageIndicatorDotRadiusSelected, com.google.android.GoogleCameraEngR18F1.R.attr.wsPageIndicatorDotShadowColor, com.google.android.GoogleCameraEngR18F1.R.attr.wsPageIndicatorDotShadowDx, com.google.android.GoogleCameraEngR18F1.R.attr.wsPageIndicatorDotShadowDy, com.google.android.GoogleCameraEngR18F1.R.attr.wsPageIndicatorDotShadowRadius, com.google.android.GoogleCameraEngR18F1.R.attr.wsPageIndicatorDotSpacing};
}
