package defpackage;

import android.hardware.display.DisplayManager;
import android.view.WindowManager;
import com.google.android.apps.camera.bottombar.BottomBarController;
import com.google.android.apps.camera.stats.timing.CameraActivityTiming;
import com.google.android.apps.camera.ui.views.MainActivityLayout;

/* JADX INFO: loaded from: classes.dex */
public final class bvl implements btu {
    private final qkg A;
    private final qkg a;
    private final qkg b;
    private final qkg c;
    private final qkg d;
    private final qkg e;
    private final qkg f;
    private final qkg g;
    private final qkg h;
    private final qkg i;
    private final qkg j;
    private final qkg k;
    private final qkg l;
    private final qkg m;
    private final qkg n;
    private final qkg o;
    private final qkg p;
    private final qkg q;
    private final qkg r;
    private final qkg s;
    private final qkg t;
    private final qkg u;
    private final qkg v;
    private final qkg w;
    private final qkg x;
    private final qkg y;
    private final qkg z;

    public bvl(qkg qkgVar, qkg qkgVar2, qkg qkgVar3, qkg qkgVar4, qkg qkgVar5, qkg qkgVar6, qkg qkgVar7, qkg qkgVar8, qkg qkgVar9, qkg qkgVar10, qkg qkgVar11, qkg qkgVar12, qkg qkgVar13, qkg qkgVar14, qkg qkgVar15, qkg qkgVar16, qkg qkgVar17, qkg qkgVar18, qkg qkgVar19, qkg qkgVar20, qkg qkgVar21, qkg qkgVar22, qkg qkgVar23, qkg qkgVar24, qkg qkgVar25, qkg qkgVar26, qkg qkgVar27) {
        qkgVar.getClass();
        this.a = qkgVar;
        qkgVar2.getClass();
        this.b = qkgVar2;
        qkgVar3.getClass();
        this.c = qkgVar3;
        qkgVar4.getClass();
        this.d = qkgVar4;
        qkgVar5.getClass();
        this.e = qkgVar5;
        qkgVar6.getClass();
        this.f = qkgVar6;
        qkgVar7.getClass();
        this.g = qkgVar7;
        qkgVar8.getClass();
        this.h = qkgVar8;
        qkgVar9.getClass();
        this.i = qkgVar9;
        qkgVar10.getClass();
        this.j = qkgVar10;
        qkgVar11.getClass();
        this.k = qkgVar11;
        this.l = qkgVar12;
        qkgVar13.getClass();
        this.m = qkgVar13;
        qkgVar14.getClass();
        this.n = qkgVar14;
        qkgVar15.getClass();
        this.o = qkgVar15;
        this.p = qkgVar16;
        qkgVar17.getClass();
        this.q = qkgVar17;
        qkgVar18.getClass();
        this.r = qkgVar18;
        qkgVar19.getClass();
        this.s = qkgVar19;
        qkgVar20.getClass();
        this.t = qkgVar20;
        qkgVar21.getClass();
        this.u = qkgVar21;
        qkgVar22.getClass();
        this.v = qkgVar22;
        qkgVar23.getClass();
        this.w = qkgVar23;
        this.x = qkgVar24;
        qkgVar25.getClass();
        this.y = qkgVar25;
        qkgVar26.getClass();
        this.z = qkgVar26;
        qkgVar27.getClass();
        this.A = qkgVar27;
    }

    @Override // defpackage.btu
    public final /* synthetic */ btv a(boolean z) {
        bts btsVar = (bts) this.a.get();
        btsVar.getClass();
        Object obj = this.b.get();
        jns jnsVar = ((jnw) this.c).get();
        jnr jnrVar = (jnr) this.d.get();
        jnrVar.getClass();
        jcf jcfVar = (jcf) this.e.get();
        jcfVar.getClass();
        jng jngVar = (jng) this.f.get();
        jngVar.getClass();
        bqg bqgVar = ((etg) this.g).get();
        Object obj2 = this.h.get();
        WindowManager windowManager = ((emh) this.i).get();
        ivj ivjVar = (ivj) this.j.get();
        ivjVar.getClass();
        ixx ixxVar = (ixx) this.k.get();
        ixxVar.getClass();
        ((mip) this.l.get()).getClass();
        buc bucVar = (buc) this.m.get();
        bucVar.getClass();
        BottomBarController bottomBarController = (BottomBarController) this.n.get();
        bottomBarController.getClass();
        jlb jlbVar = (jlb) this.o.get();
        jlbVar.getClass();
        epj epjVar = (epj) this.p.get();
        epjVar.getClass();
        fjs fjsVar = (fjs) this.q.get();
        fjsVar.getClass();
        CameraActivityTiming cameraActivityTiming = (CameraActivityTiming) this.r.get();
        cameraActivityTiming.getClass();
        qkg qkgVar = this.s;
        jfn jfnVar = (jfn) this.t.get();
        jfnVar.getClass();
        jak jakVar = (jak) this.u.get();
        jakVar.getClass();
        gtg gtgVar = (gtg) this.v.get();
        gtgVar.getClass();
        jjp jjpVar = (jjp) this.w.get();
        jjpVar.getClass();
        pih pihVar = (pih) this.x.get();
        pihVar.getClass();
        dju djuVar = (dju) this.y.get();
        djuVar.getClass();
        ddf ddfVar = (ddf) this.z.get();
        ddfVar.getClass();
        hoj hojVar = (hoj) this.A.get();
        hojVar.getClass();
        return new bvk(btsVar, (MainActivityLayout) obj, jnsVar, jnrVar, jcfVar, jngVar, bqgVar, (DisplayManager) obj2, windowManager, ivjVar, ixxVar, bucVar, bottomBarController, jlbVar, epjVar, fjsVar, cameraActivityTiming, qkgVar, jfnVar, jakVar, gtgVar, jjpVar, pihVar, djuVar, ddfVar, hojVar, z);
    }
}
