package defpackage;

/* JADX INFO: loaded from: classes.dex */
public final class cfz implements cfw {
    public final qkg A;
    public final qkg a;
    public final qkg b;
    public final qkg c;
    public final qkg d;
    public final qkg e;
    public final qkg f;
    public final qkg g;
    public final qkg h;
    public final qkg i;
    public final qkg j;
    public final qkg k;
    public final qkg l;
    public final qkg m;
    public final qkg n;
    public final qkg o;
    public final qkg p;
    public final qkg q;
    public final qkg r;
    public final qkg s;
    public final qkg t;
    public final qkg u;
    public final qkg v;
    public final qkg w;
    public final qkg x;
    public final qkg y;
    public final qkg z;

    public cfz(qkg qkgVar, qkg qkgVar2, qkg qkgVar3, qkg qkgVar4, qkg qkgVar5, qkg qkgVar6, qkg qkgVar7, qkg qkgVar8, qkg qkgVar9, qkg qkgVar10, qkg qkgVar11, qkg qkgVar12, qkg qkgVar13, qkg qkgVar14, qkg qkgVar15, qkg qkgVar16, qkg qkgVar17, qkg qkgVar18, qkg qkgVar19, qkg qkgVar20, qkg qkgVar21, qkg qkgVar22, qkg qkgVar23, qkg qkgVar24, qkg qkgVar25, qkg qkgVar26, qkg qkgVar27) {
        qkgVar.getClass();
        this.a = qkgVar;
        qkgVar2.getClass();
        this.b = qkgVar2;
        qkgVar3.getClass();
        this.c = qkgVar3;
        this.d = qkgVar4;
        qkgVar5.getClass();
        this.e = qkgVar5;
        qkgVar6.getClass();
        this.f = qkgVar6;
        qkgVar7.getClass();
        this.g = qkgVar7;
        qkgVar8.getClass();
        this.h = qkgVar8;
        qkgVar9.getClass();
        this.i = qkgVar9;
        qkgVar10.getClass();
        this.j = qkgVar10;
        qkgVar11.getClass();
        this.k = qkgVar11;
        qkgVar12.getClass();
        this.l = qkgVar12;
        qkgVar13.getClass();
        this.m = qkgVar13;
        qkgVar14.getClass();
        this.n = qkgVar14;
        qkgVar15.getClass();
        this.o = qkgVar15;
        qkgVar16.getClass();
        this.p = qkgVar16;
        qkgVar17.getClass();
        this.q = qkgVar17;
        qkgVar18.getClass();
        this.r = qkgVar18;
        qkgVar19.getClass();
        this.s = qkgVar19;
        qkgVar20.getClass();
        this.t = qkgVar20;
        qkgVar21.getClass();
        this.u = qkgVar21;
        qkgVar22.getClass();
        this.v = qkgVar22;
        qkgVar23.getClass();
        this.w = qkgVar23;
        this.x = qkgVar24;
        this.y = qkgVar25;
        qkgVar26.getClass();
        this.z = qkgVar26;
        qkgVar27.getClass();
        this.A = qkgVar27;
    }
}
