package defpackage;

import com.google.android.apps.camera.bottombar.R;
import java.util.Map;

/* JADX INFO: loaded from: classes3.dex */
public final class dcu {
    public static final ddg A;
    public static final ddg B;
    public static final ddg C;
    public static final ddg D;
    public static final ddg E;
    public static final ddg F;
    public static final ddg G;
    public static final ddg H;
    public static final ddg I;
    public static final ddg J;
    public static final ddg K;
    public static final ddg L;
    public static final ddg M;
    public static final ddg N;
    public static final ddg O;
    public static final ddg P;
    public static final ddg Q;
    public static final ddg R;
    public static final ddg S;
    public static final ddg T;
    public static final ddg U;
    public static final ddg V;
    public static final ddg W;
    public static final ddg X;
    public static final ddg Y;
    public static final ddg Z;
    public static final ddi a;
    public static final ddg aa;
    public static final ddg ab;
    public static final ddg ac;
    public static final ddg ad;
    public static final ddg ae;
    public static final ddg af;
    public static final ddg ag;
    public static final ddi b;
    public static final ddi c;
    public static final ddi d;
    public static final ddi e;
    public static final ddi f;
    public static final ddi g;
    public static final ddi h;
    public static final ddi i;
    public static final ddi j;
    public static final ddi k;
    public static final ddg l;
    public static final ddg m;
    public static final ddg n;
    public static final ddg o;
    public static final ddg p;
    public static final ddg q;
    public static final ddg r;
    public static final ddg s;
    public static final ddg t;
    public static final ddg u;
    public static final ddg v;
    public static final ddg w;
    public static final ddg x;
    public static final ddg y;
    public static final ddg z;

    static {
        ddh ddhVar = new ddh();
        ddhVar.a = "camcorder.bitrate";
        a = ddhVar.a();
        ddh ddhVar2 = new ddh();
        ddhVar2.a = "camcorder.capture_rate";
        ddhVar2.c = ope.L(0, 30, 60, Integer.valueOf(R.styleable.AppCompatTheme_windowFixedHeightMajor), 240);
        b = ddhVar2.a();
        ddh ddhVar3 = new ddh();
        ddhVar3.a = "detect_face_on_front_camera";
        l = ddhVar3.f();
        ddh ddhVar4 = new ddh();
        ddhVar4.a = "detect_face_on_non_front_camera";
        m = ddhVar4.f();
        new ddh().a = "camcorder.fragmented_muxer";
        ddh ddhVar5 = new ddh();
        ddhVar5.a = "camcorder_slowmo.fs";
        n = ddhVar5.c();
        new ddh().a = "camcorder.h265";
        ddh ddhVar6 = new ddh();
        ddhVar6.a = "enable_hevc_setting";
        o = ddhVar6.f();
        ddh ddhVar7 = new ddh();
        ddhVar7.a = "camcorder.codec_sm";
        p = ddhVar7.f();
        ddh ddhVar8 = new ddh();
        ddhVar8.a = "camcorder.codec_video";
        q = ddhVar8.f();
        new ddh().a = "camcorder.no_audio";
        ddh ddhVar9 = new ddh();
        ddhVar9.a = "camcorder.enable_sapphire";
        r = ddhVar9.f();
        ddh ddhVar10 = new ddh();
        ddhVar10.a = "camcorder.ois";
        s = ddhVar10.d();
        ddh ddhVar11 = new ddh();
        ddhVar11.a = "camcorder.stereo";
        t = ddhVar11.d();
        new ddh().a = "camcorder.sf_share";
        ddh ddhVar12 = new ddh();
        ddhVar12.a = "camcorder.trk_yuv";
        u = ddhVar12.c();
        new ddh().a = "camcorder.viewfinder_effect";
        new ddh().a = "camcorder.vfe_limit_30fps";
        ddh ddhVar13 = new ddh();
        ddhVar13.a = "fps_video_setting_writeable";
        v = ddhVar13.f();
        ddh ddhVar14 = new ddh();
        ddhVar14.a = "google_llv_30_fps_non_4k";
        w = ddhVar14.f();
        ddh ddhVar15 = new ddh();
        ddhVar15.a = "google_llv_auto_fps_non_4k";
        x = ddhVar15.f();
        ddh ddhVar16 = new ddh();
        ddhVar16.a = "max_1080p_video_duration_seconds";
        c = ddhVar16.a();
        ddh ddhVar17 = new ddh();
        ddhVar17.a = "max_2160p_video_duration_seconds";
        d = ddhVar17.a();
        ddh ddhVar18 = new ddh();
        ddhVar18.a = "max_hfr_video_duration_seconds";
        e = ddhVar18.a();
        ddh ddhVar19 = new ddh();
        ddhVar19.a = "UNLOCK_AF_AE_WITH_SCENE_CHANGE_FOR_FRONT_CAM";
        y = ddhVar19.f();
        ddh ddhVar20 = new ddh();
        ddhVar20.a = "camcorder.vidqual_front";
        ddhVar20.c = ope.M(144, 240, 288, 480, 720, 1080, 2160);
        f = ddhVar20.a();
        ddh ddhVar21 = new ddh();
        ddhVar21.a = "camcorder.vidqual_back";
        ddhVar21.c = ope.M(144, 240, 288, 480, 720, 1080, 2160);
        g = ddhVar21.a();
        ddh ddhVar22 = new ddh();
        ddhVar22.a = "zoom_override_enabled";
        z = ddhVar22.f();
        ddh ddhVar23 = new ddh();
        ddhVar23.a = "camcorder.max_zoom_30fps";
        A = ddhVar23.e();
        ddh ddhVar24 = new ddh();
        ddhVar24.a = "camcorder.max_zoom_default";
        B = ddhVar24.e();
        ddh ddhVar25 = new ddh();
        ddhVar25.a = "camcorder_prewire_record_surface";
        C = ddhVar25.f();
        ddh ddhVar26 = new ddh();
        ddhVar26.a = "camcorder_recorder_warm_up";
        D = ddhVar26.f();
        new ddh().a = "camcorder.24fps";
        ddh ddhVar27 = new ddh();
        ddhVar27.a = "camcorder.4k60fps";
        E = ddhVar27.f();
        ddh ddhVar28 = new ddh();
        ddhVar28.a = "camcorder.stokes_dyn";
        F = ddhVar28.f();
        ddh ddhVar29 = new ddh();
        ddhVar29.a = "camcorder.stokes_thr";
        G = ddhVar29.f();
        ddh ddhVar30 = new ddh();
        ddhVar30.a = "camcorder.stokes_mra";
        H = ddhVar30.f();
        ddh ddhVar31 = new ddh();
        ddhVar31.a = "camcorder.stokes_asm";
        I = ddhVar31.f();
        new ddh().a = "camcorder.poll";
        ddh ddhVar32 = new ddh();
        ddhVar32.a = "camcorder.submode";
        ddhVar32.c = ope.J(0, 1, 2);
        h = ddhVar32.a();
        ddh ddhVar33 = new ddh();
        ddhVar33.a = "camcorder.washington_md";
        ddhVar33.c = ope.L(0, 1, 2, 3, 4);
        i = ddhVar33.a();
        ddh ddhVar34 = new ddh();
        ddhVar34.a = "camcorder.enable_dumpling";
        J = ddhVar34.f();
        new ddh().a = "camcorder.enable_w_poll";
        ddh ddhVar35 = new ddh();
        ddhVar35.a = "camcorder.slowmo_snapshot";
        K = ddhVar35.f();
        new ddh().a = "camcorder.screenshot_snapshot";
        ddh ddhVar36 = new ddh();
        ddhVar36.a = "camcorder.washington";
        L = ddhVar36.f();
        ddh ddhVar37 = new ddh();
        ddhVar37.a = "camcorder.washington_edu";
        M = ddhVar37.f();
        ddh ddhVar38 = new ddh();
        ddhVar38.a = "camcorder.ext_mic_state";
        ddhVar38.c = ope.K(0, 1, 2, 3);
        j = ddhVar38.a();
        ddh ddhVar39 = new ddh();
        ddhVar39.a = "camcorder.use_gcamux";
        N = ddhVar39.f();
        ddh ddhVar40 = new ddh();
        ddhVar40.a = "camcorder.video_file_max_size";
        O = new ddg(ddhVar40.a, ddhVar40.b);
        ddh ddhVar41 = new ddh();
        ddhVar41.a = "camcorder.3a_metadata";
        P = ddhVar41.f();
        ddh ddhVar42 = new ddh();
        ddhVar42.a = "camcorder.fix_crtime";
        Q = ddhVar42.f();
        ddh ddhVar43 = new ddh();
        ddhVar43.a = "camcorder.fb_preview";
        R = ddhVar43.f();
        ddh ddhVar44 = new ddh();
        ddhVar44.a = "camcorder.animate_stab_button";
        S = ddhVar44.f();
        ddh ddhVar45 = new ddh();
        ddhVar45.a = "camcorder.washington_l";
        T = ddhVar45.f();
        ddh ddhVar46 = new ddh();
        ddhVar46.a = "camcorder.washington_a";
        U = ddhVar46.f();
        ddh ddhVar47 = new ddh();
        ddhVar47.a = "camcorder.washington_c";
        V = ddhVar47.f();
        ddh ddhVar48 = new ddh();
        ddhVar48.a = "camcorder.slowmo_pause";
        W = ddhVar48.f();
        ddh ddhVar49 = new ddh();
        ddhVar49.a = "camcorder.sync_fps";
        X = ddhVar49.f();
        new ddh().a = "camcorder.log_3a";
        ddh ddhVar50 = new ddh();
        ddhVar50.a = "camcorder.auto_stop_on_frame_drop";
        Y = ddhVar50.c();
        ddh ddhVar51 = new ddh();
        ddhVar51.a = "camcorder.camera_perfetto_trace_frame_drops";
        ddhVar51.b = "General";
        ddh ddhVar52 = new ddh();
        ddhVar52.a = "g";
        ddhVar52.b = "General";
        k = ddhVar52.a();
        new ddh().a = "camcorder.ir_fs";
        ddh ddhVar53 = new ddh();
        ddhVar53.a = "camcorder.front_variable_fps_range";
        Z = ddhVar53.f();
        ddh ddhVar54 = new ddh();
        ddhVar54.a = "camcorder.ts";
        aa = ddhVar54.f();
        ddh ddhVar55 = new ddh();
        ddhVar55.a = "camcorder.ap";
        ab = ddhVar55.f();
        ddh ddhVar56 = new ddh();
        ddhVar56.a = "camcorder.sm";
        ac = ddhVar56.f();
        new ddh().a = "camcorder.sm_r";
        new ddh().a = "camcorder.sm_no_fallback";
        new ddh().a = "camcorder.sm_setting_force_on";
        new ddh().a = "camcorder.sm_use_face";
        ddh ddhVar57 = new ddh();
        ddhVar57.a = "camcorder.sm_nf";
        ad = ddhVar57.e();
        ddh ddhVar58 = new ddh();
        ddhVar58.a = "camcorder.use_bt709";
        ae = ddhVar58.f();
        ddh ddhVar59 = new ddh();
        ddhVar59.a = "camcorder.add_silent_audio";
        af = ddhVar59.f();
        new ddh().a = "camcorder.default_resolution_4K";
        ddh ddhVar60 = new ddh();
        ddhVar60.a = "camcorder.1080p60_thr";
        ag = ddhVar60.f();
    }

    public static void a(ddk ddkVar, lzh lzhVar) {
        ner nerVarC;
        ddkVar.o(a, null);
        ddkVar.o(b, null);
        ddkVar.s(l, true);
        ddkVar.s(m, true);
        ddkVar.p(n);
        ddkVar.s(o, true);
        ddkVar.s(p, true);
        ddkVar.s(q, true);
        ddkVar.s(r, false);
        ddkVar.q(s, true);
        ddkVar.q(t, lzhVar.e);
        ddkVar.p(u);
        ddkVar.s(v, true);
        ddkVar.o(c, 0);
        ddkVar.o(d, 0);
        ddkVar.o(e, 300);
        ddkVar.s(w, true);
        ddkVar.s(x, true);
        ddkVar.s(y, false);
        ddkVar.o(f, null);
        ddkVar.o(g, null);
        ddkVar.s(z, true);
        ddkVar.r(A, Float.valueOf(5.0f));
        ddkVar.r(B, Float.valueOf(3.0f));
        ddkVar.s(C, false);
        ddkVar.s(D, false);
        ddkVar.s(E, false);
        ddkVar.s(F, false);
        ddkVar.s(G, false);
        ddkVar.s(H, false);
        ddkVar.s(I, false);
        ddkVar.o(h, 1);
        ddkVar.s(K, false);
        ddkVar.s(L, true);
        ddkVar.s(M, false);
        ddkVar.o(j, 1);
        ddkVar.s(N, true);
        ddg ddgVar = O;
        Long l2 = 10737418240L;
        Map map = ((dep) ddkVar).b;
        String str = ddgVar.b;
        if (str != null) {
            String str2 = ddgVar.a;
            nep nepVar = del.a;
            StringBuilder sb = new StringBuilder(str.length() + 2 + String.valueOf(str2).length());
            sb.append(str);
            sb.append("__");
            sb.append(str2);
            nerVarC = ner.c(nepVar, sb.toString(), Long.valueOf(l2.longValue()), false);
        } else {
            nerVarC = null;
        }
        map.put(ddgVar, new dem(l2, nerVarC));
        ddkVar.s(P, false);
        ddkVar.o(i, null);
        ddkVar.s(J, true);
        ddkVar.s(Q, true);
        ddkVar.s(R, false);
        ddkVar.s(S, false);
        ddkVar.s(T, true);
        ddkVar.s(U, true);
        ddkVar.s(V, true);
        ddkVar.s(W, true);
        ddkVar.s(X, true);
        ddkVar.p(Y);
        boolean z2 = lzhVar.f;
        ddkVar.o(k, 6);
        ddkVar.s(Z, true);
        ddkVar.s(aa, false);
        ddkVar.s(ab, false);
        ddkVar.s(ac, false);
        ddkVar.r(ad, Float.valueOf(0.2f));
        ddkVar.s(af, true);
        ddkVar.s(ae, true);
        ddkVar.s(ag, false);
    }
}
