package defpackage;

import com.Fix.Pref;
import java.util.concurrent.TimeUnit;

/* JADX INFO: loaded from: classes3.dex */
public final class ddl {
    public static final ddi A;
    public static final ddi B;
    public static final ddi C;
    public static final ddi D;
    public static final ddi E;
    public static final ddi F;
    public static final ddi G;
    public static final ddi H;
    public static final ddg I;
    public static final ddg J;
    public static final ddg K;
    public static final ddg L;
    public static final ddg M;
    public static final ddg N;
    public static final ddg O;
    public static final ddg P;
    public static final ddg Q;
    public static final ddg R;
    public static final ddg S;
    public static final ddg T;
    public static final ddg U;
    public static final ddg V;
    public static final ddg W;
    public static final ddg X;
    public static final ddg Y;
    public static final ddg Z;
    public static final ddi a;
    public static final ddg aA;
    public static final ddg aB;
    public static final ddg aC;
    public static final ddg aD;
    public static final ddg aE;
    public static final ddg aF;
    public static final ddg aG;
    public static final ddg aH;
    public static final ddg aI;
    public static final ddg aJ;
    public static final ddg aK;
    public static final ddg aL;
    public static final ddg aM;
    public static final ddg aN;
    public static final ddg aO;
    public static final ddg aP;
    public static final ddg aQ;
    public static final ddg aR;
    public static final ddg aS;
    public static final ddg aT;
    public static final ddg aU;
    public static final ddg aV;
    public static final ddg aW;
    public static final ddg aX;
    public static final ddg aY;
    public static final ddg aZ;
    public static final ddg aa;
    public static final ddg ab;
    public static final ddg ac;
    public static final ddg ad;
    public static final ddg ae;
    public static final ddg af;
    public static final ddg ag;
    public static final ddg ah;
    public static final ddg ai;
    public static final ddg aj;
    public static final ddg ak;
    public static final ddg al;
    public static final ddg am;
    public static final ddg an;
    public static final ddg ao;
    public static final ddg ap;
    public static final ddg aq;
    public static final ddg ar;
    public static final ddg as;
    public static final ddg at;
    public static final ddg au;
    public static final ddg av;
    public static final ddg aw;
    public static final ddg ax;
    public static final ddg ay;
    public static final ddg az;
    public static final ddi b;
    public static final ddg ba;
    public static final ddg bb;
    public static final ddg bc;
    public static final ddg bd;
    public static final ddg be;
    public static final ddg bf;
    public static final ddg bg;
    public static final ddg bh;
    public static final ddg bi;
    public static final ddg bj;
    public static final ddg bk;
    public static final ddg bl;
    public static final ddg bm;
    public static final ddg bn;
    public static final ddg bo;
    public static final ddg bp;
    public static final ddg bq;
    public static final ddg br;
    public static final ddg bs;
    public static final ddg bt;
    public static final ddg bu;
    public static final ddi c;
    public static final ddi d;
    public static final ddi e;
    public static final ddi f;
    public static final ddi g;
    public static final ddi h;
    public static final ddi i;
    public static final ddi j;
    public static final ddi k;
    public static final ddi l;
    public static final ddi m;
    public static final ddi n;
    public static final ddi o;
    public static final ddi p;
    public static final ddi q;
    public static final ddi r;
    public static final ddi s;
    public static final ddi t;
    public static final ddi u;
    public static final ddi v;
    public static final ddi w;
    public static final ddi x;
    public static final ddi y;
    public static final ddi z;

    static {
        ddh ddhVar = new ddh();
        ddhVar.a = "camera.scudo_caching";
        I = ddhVar.f();
        ddh ddhVar2 = new ddh();
        ddhVar2.a = "camera.bind_assistant";
        J = ddhVar2.f();
        ddh ddhVar3 = new ddh();
        ddhVar3.a = "camera.audio_zoom";
        K = ddhVar3.f();
        new ddh().a = "camera.flash.ind";
        ddh ddhVar4 = new ddh();
        ddhVar4.a = "camera.auto_fps_default";
        L = ddhVar4.f();
        ddh ddhVar5 = new ddh();
        ddhVar5.a = "camera.auto_fps";
        M = ddhVar5.d();
        ddh ddhVar6 = new ddh();
        ddhVar6.a = "avc_profile_high_supported";
        N = ddhVar6.f();
        ddh ddhVar7 = new ddh();
        ddhVar7.a = "back_flash_off_by_default";
        O = ddhVar7.f();
        ddh ddhVar8 = new ddh();
        ddhVar8.a = "blacklisted_resolutions_back";
        P = ddhVar8.g();
        ddh ddhVar9 = new ddh();
        ddhVar9.a = "blacklisted_resolutions_front";
        Q = ddhVar9.g();
        ddh ddhVar10 = new ddh();
        ddhVar10.a = "blacklisted_preview_resolutions_back";
        R = ddhVar10.g();
        ddh ddhVar11 = new ddh();
        ddhVar11.a = "blacklisted_preview_resolutions_front";
        S = ddhVar11.g();
        new ddh().a = "camera.narrow_cam";
        ddh ddhVar12 = new ddh();
        ddhVar12.a = "camera.p20_lens_setup";
        T = ddhVar12.f();
        ddh ddhVar13 = new ddh();
        ddhVar13.a = "camera.p21_front_setup";
        U = ddhVar13.f();
        ddh ddhVar14 = new ddh();
        ddhVar14.a = "camera.toggle_zoom_bar";
        V = ddhVar14.f();
        new ddh().a = "camera.zoom_decimal_point";
        ddh ddhVar15 = new ddh();
        ddhVar15.a = "camera_zoom_toggle_long_press_duration_ms";
        ddhVar15.b = "Zoom";
        a = ddhVar15.a();
        ddh ddhVar16 = new ddh();
        ddhVar16.a = "camera_zoom_slider_tap_to_show";
        ddhVar16.b = "Zoom";
        W = ddhVar16.f();
        new ddh().a = "camera.wide_cam";
        ddh ddhVar17 = new ddh();
        ddhVar17.a = "ripper_embedded";
        X = ddhVar17.f();
        ddh ddhVar18 = new ddh();
        ddhVar18.a = "camera.enable_hw_buff_uflag";
        Y = ddhVar18.f();
        new ddh().a = "camera.chk_anim_trnstns";
        new ddh().a = "camera.disable_phenotype";
        new ddh().a = "camera.disable_clearcut";
        new ddh().a = "camera.clearcut_debug";
        ddh ddhVar19 = new ddh();
        ddhVar19.a = "contact_us_mailing_list_address_default";
        Z = ddhVar19.h();
        ddh ddhVar20 = new ddh();
        ddhVar20.a = "contact_us_mailing_list_address_for_droid_canary_and_fishfood";
        aa = ddhVar20.h();
        ddh ddhVar21 = new ddh();
        ddhVar21.a = "contact_us_mailing_list_address_for_google_food";
        ab = ddhVar21.h();
        new ddh().a = "camera.vid_meta_fatal";
        new ddh().a = "camera.developer.enable";
        ddh ddhVar22 = new ddh();
        ddhVar22.a = "camera.fake_therm_state";
        b = ddhVar22.a();
        new ddh().a = "camera.ignore_temp";
        new ddh().a = "camera.mock_low_storage";
        ddh ddhVar23 = new ddh();
        ddhVar23.a = "early_focus_unlock";
        ac = ddhVar23.f();
        new ddh().a = "camera.elmyra_lens";
        new ddh().a = "camera.photo_fixed_framerate";
        new ddh().a = "camera.elmyra_assist";
        new ddh().a = "camera.debug_hw_ver";
        ddh ddhVar24 = new ddh();
        ddhVar24.a = "exif_model_make_sanitization_enabled";
        ad = ddhVar24.f();
        new ddh().a = "camera.exp.activity";
        ddh ddhVar25 = new ddh();
        ddhVar25.a = "camera.faceannouncer";
        ae = ddhVar25.c();
        new ddh().a = "camera.faceboxes";
        ddh ddhVar26 = new ddh();
        ddhVar26.a = "camera.first_preview_frame";
        c = ddhVar26.a();
        ddh ddhVar27 = new ddh();
        ddhVar27.a = "camera.video_preview_frame_extra_delay";
        d = ddhVar27.a();
        ddh ddhVar28 = new ddh();
        ddhVar28.a = "camera.vfe.skip_first_frame";
        af = ddhVar28.f();
        new ddh().a = "camera.debug.overlay";
        new ddh().a = "camera.debug.overlay_info_def";
        new ddh().a = "camera.debug.overlay_info_ff";
        new ddh().a = "camera.debug.overlay_af_saliency";
        new ddh().a = "camera.debug.overlay_af_smartroi";
        ddh ddhVar29 = new ddh();
        ddhVar29.a = "filmstrip_tiny_bounds";
        e = ddhVar29.a();
        ddh ddhVar30 = new ddh();
        ddhVar30.a = "filmstrip_maximum_smooth_pixels";
        f = ddhVar30.a();
        new ddh().a = "camera.focus.debug";
        ddh ddhVar31 = new ddh();
        ddhVar31.a = "camera.front.flashColor";
        g = ddhVar31.a();
        ddh ddhVar32 = new ddh();
        ddhVar32.a = "camera.front_torch_request";
        ag = ddhVar32.d();
        ddh ddhVar33 = new ddh();
        ddhVar33.a = "camera.front.backgroundIlluminationColor";
        h = ddhVar33.a();
        ddh ddhVar34 = new ddh();
        ddhVar34.a = "camera.front.viewfinderIlluminationColor";
        i = ddhVar34.a();
        ddh ddhVar35 = new ddh();
        ddhVar35.a = "camera.front.translucentSelfieIllumination";
        ah = ddhVar35.f();
        ddh ddhVar36 = new ddh();
        ddhVar36.a = "google_lens_enabled";
        ai = ddhVar36.f();
        ddh ddhVar37 = new ddh();
        ddhVar37.a = "google_lens_min_supported_photos_app_version";
        aj = ddhVar37.g();
        ddh ddhVar38 = new ddh();
        ddhVar38.a = "camera_hermes_enabled";
        ddhVar38.b = "General";
        ak = ddhVar38.f();
        ddh ddhVar39 = new ddh();
        ddhVar39.a = "camera_hermes_gc_enabled";
        ddhVar39.b = "General";
        al = ddhVar39.f();
        ddh ddhVar40 = new ddh();
        ddhVar40.a = "camera_hermes_interval_seconds";
        ddhVar40.b = "General";
        j = ddhVar40.a();
        ddh ddhVar41 = new ddh();
        ddhVar41.a = "hermes_activity_finish_millis";
        k = ddhVar41.a();
        ddh ddhVar42 = new ddh();
        ddhVar42.a = "high_performance_ipe_supported";
        am = ddhVar42.f();
        ddh ddhVar43 = new ddh();
        ddhVar43.a = "hybrid_ae_only_ois_jitter_for_back_camera_enabled";
        an = ddhVar43.f();
        ddh ddhVar44 = new ddh();
        ddhVar44.a = "hybrid_ae_supported";
        ao = ddhVar44.f();
        ddh ddhVar45 = new ddh();
        ddhVar45.a = "camera.enable_lkcnry";
        ap = ddhVar45.c();
        ddh ddhVar46 = new ddh();
        ddhVar46.a = "camera.use_local_logger";
        aq = ddhVar46.f();
        ddh ddhVar47 = new ddh();
        ddhVar47.a = "camera.use_perf_logger";
        ar = ddhVar47.f();
        ddh ddhVar48 = new ddh();
        ddhVar48.a = "camera.logger_throttle_millis";
        l = ddhVar48.a();
        ddh ddhVar49 = new ddh();
        ddhVar49.a = "max_allowed_allocator_memory_mb";
        m = ddhVar49.a();
        ddh ddhVar50 = new ddh();
        ddhVar50.a = "max_allowed_native_memory_mb";
        n = ddhVar50.a();
        ddh ddhVar51 = new ddh();
        ddhVar51.a = "measure_integration_enabled";
        as = ddhVar51.f();
        ddh ddhVar52 = new ddh();
        ddhVar52.a = "ois_api_supported";
        at = ddhVar52.f();
        ddh ddhVar53 = new ddh();
        ddhVar53.a = "ois_api_version";
        o = ddhVar53.a();
        ddh ddhVar54 = new ddh();
        ddhVar54.a = "camera.onscreen_logcat";
        au = ddhVar54.b();
        ddh ddhVar55 = new ddh();
        ddhVar55.a = "camera.onscreen_log";
        av = ddhVar55.b();
        new ddh().a = "selfie_mirror_log";
        ddh ddhVar56 = new ddh();
        ddhVar56.a = "p20_shutter_btn.enabled.RESTART";
        aw = ddhVar56.f();
        ddh ddhVar57 = new ddh();
        ddhVar57.a = "p_or_higher";
        ax = ddhVar57.f();
        ddh ddhVar58 = new ddh();
        ddhVar58.a = "mn_enabled";
        ay = ddhVar58.f();
        new ddh().a = "mn_settings_enabled";
        new ddh().a = "perfetto_trigger";
        ddh ddhVar59 = new ddh();
        ddhVar59.a = "camera_perfetto_trigger_millis";
        ddhVar59.b = "General";
        p = ddhVar59.a();
        ddh ddhVar60 = new ddh();
        ddhVar60.a = "camera.prod_testing";
        az = ddhVar60.f();
        ddh ddhVar61 = new ddh();
        ddhVar61.a = "camera.progress_overlay";
        aA = ddhVar61.c();
        new ddh().a = "mcfly_enabled";
        new ddh().a = "camera.enable_rocky";
        ddh ddhVar62 = new ddh();
        ddhVar62.a = "camera.enable_zebras";
        aB = ddhVar62.f();
        ddh ddhVar63 = new ddh();
        ddhVar63.a = "camera.zebras_others";
        aC = ddhVar63.f();
        new ddh().a = "fatal_error_sql_error_checks_enabled";
        ddh ddhVar64 = new ddh();
        ddhVar64.a = "camera.shot_tracking";
        aD = ddhVar64.f();
        new ddh().a = "camera.shot_tracking.sql_checks";
        ddh ddhVar65 = new ddh();
        ddhVar65.a = "camera.shot_tracking.stuck_age_seconds";
        q = ddhVar65.a();
        ddh ddhVar66 = new ddh();
        ddhVar66.a = "pd_calibration_data_supported";
        aE = ddhVar66.f();
        ddh ddhVar67 = new ddh();
        ddhVar67.a = "camera.60fps";
        aF = ddhVar67.d();
        ddh ddhVar68 = new ddh();
        ddhVar68.a = "unflipped_selfie_default";
        aG = ddhVar68.f();
        new ddh().a = "scripting_enabled";
        ddh ddhVar69 = new ddh();
        ddhVar69.a = "camera_slow_launch_dialog_trigger_ms";
        ddhVar69.b = "General";
        r = ddhVar69.a();
        ddh ddhVar70 = new ddh();
        ddhVar70.a = "enable_social_share";
        ddhVar70.b = "SocialShare";
        aH = ddhVar70.f();
        ddh ddhVar71 = new ddh();
        ddhVar71.a = "enable_bounce_animation_on_social_share_menu";
        aI = ddhVar71.f();
        ddh ddhVar72 = new ddh();
        ddhVar72.a = "camera.obfuscation_share_enabled";
        aJ = ddhVar72.f();
        ddh ddhVar73 = new ddh();
        ddhVar73.a = "squeeze_supported";
        aK = ddhVar73.f();
        new ddh().a = "camera.strict_vm";
        new ddh().a = "camera.strict_vm_die_on_violation";
        new ddh().a = "camera.strict_vm_visual_warning_on_violation";
        new ddh().a = "camera.strict_vm_diskread";
        new ddh().a = "camera.syshealth_info";
        new ddh().a = "camera.memory_monitor_overlay";
        ddh ddhVar74 = new ddh();
        ddhVar74.a = "camera.double_tap_launch_bottom_sheet";
        s = ddhVar74.a();
        new ddh().a = "camera.dbg.bugtoast";
        ddh ddhVar75 = new ddh();
        ddhVar75.a = "camera.skip_oobe";
        aL = ddhVar75.f();
        ddh ddhVar76 = new ddh();
        ddhVar76.a = "camera.extra_zoom_linger";
        aM = ddhVar76.f();
        ddh ddhVar77 = new ddh();
        ddhVar77.a = "camera.location_default";
        aN = ddhVar77.f();
        new ddh().a = "camera.vfe.poc_gray";
        new ddh().a = "camera.vfe.debugbar";
        ddh ddhVar78 = new ddh();
        ddhVar78.a = "camera.double_tap_launch_edu_enabled";
        aO = ddhVar78.f();
        ddh ddhVar79 = new ddh();
        ddhVar79.a = "camera.auto_timer_enabled";
        aP = ddhVar79.f();
        new ddh().a = "use_pck_storage";
        ddh ddhVar80 = new ddh();
        ddhVar80.a = "unflipped_selfie_enabled";
        aQ = ddhVar80.f();
        ddh ddhVar81 = new ddh();
        ddhVar81.a = "use_physical_raw";
        aR = ddhVar81.f();
        ddh ddhVar82 = new ddh();
        ddhVar82.a = "camera.pck_large_yuv";
        aS = ddhVar82.f();
        new ddh().a = "use_minimal_q_storage_v2";
        ddh ddhVar83 = new ddh();
        ddhVar83.a = "camera.no_media_type_none_on_q_or_above";
        aT = ddhVar83.f();
        ddh ddhVar84 = new ddh();
        ddhVar84.a = "use_immersive_rounded_corners";
        aU = ddhVar84.f();
        ddh ddhVar85 = new ddh();
        ddhVar85.a = "camera.ddepth_rear";
        aV = ddhVar85.f();
        ddh ddhVar86 = new ddh();
        ddhVar86.a = "camera.ddepth_front";
        aW = ddhVar86.f();
        new ddh().a = "camera.ddepth_debug";
        ddh ddhVar87 = new ddh();
        ddhVar87.a = "camera.ddepth_preference_override";
        aX = ddhVar87.f();
        new ddh().a = "camera.ddepth_rear_use_opencl";
        new ddh().a = "camera.alloc_tracker";
        new ddh().a = "camera.mediafile_stuck_notification";
        new ddh().a = "camera.mediafile_stuck_crash";
        new ddh().a = "camera.custom_hotkeys";
        ddh ddhVar88 = new ddh();
        ddhVar88.a = "camera.no_low_fb";
        aY = ddhVar88.f();
        new ddh().a = "camera.fb_hcheck";
        new ddh().a = "camera.log_frame_availability";
        ddh ddhVar89 = new ddh();
        ddhVar89.a = "camera.allow_fine_haptics";
        aZ = ddhVar89.f();
        new ddh().a = "camera.jankmonitor_full";
        ddh ddhVar90 = new ddh();
        ddhVar90.a = "camera.sparrow";
        ba = ddhVar90.f();
        new ddh().a = "camera.crash_unknown_thermal_status";
        new ddh().a = "camera.dots_of_doom";
        ddh ddhVar91 = new ddh();
        ddhVar91.b = "Beholder";
        ddhVar91.a = "beholder_enabled";
        bb = ddhVar91.f();
        ddh ddhVar92 = new ddh();
        ddhVar92.b = "Beholder";
        ddhVar92.a = "beholder_example_sensor_buffer_size";
        t = ddhVar92.a();
        ddh ddhVar93 = new ddh();
        ddhVar93.b = "Beholder";
        ddhVar93.a = "beholder_no_training_threshold";
        u = ddhVar93.a();
        ddh ddhVar94 = new ddh();
        ddhVar94.b = "Beholder";
        ddhVar94.a = "beholder_population_name";
        bc = ddhVar94.g();
        ddh ddhVar95 = new ddh();
        ddhVar95.b = "Beholder";
        ddhVar95.a = "beholder_suggestion_enabled";
        new ddh().a = "camera.ica_in_front_enabled";
        new ddh().a = "test_only_beholder_e2e";
        ddh ddhVar96 = new ddh();
        ddhVar96.a = "beholder_save_frame";
        bd = ddhVar96.f();
        ddh ddhVar97 = new ddh();
        ddhVar97.a = "beholder_save_session";
        be = ddhVar97.f();
        new ddh().a = "test_only_beholder_enabled";
        new ddh().a = "camera.beholder_force_opt_in";
        new ddh().a = "camera.nga_direct_actions";
        new ddh().a = "camera.enable_guava_verbose_futures";
        new ddh().a = "camera.gl.log_caller_stacktrace";
        new ddh().a = "camera.gl.log_contexts";
        new ddh().a = "camera.gl.crash_if_exec_rejected";
        ddh ddhVar98 = new ddh();
        ddhVar98.a = "camera.storage_space_override";
        v = ddhVar98.a();
        ddh ddhVar99 = new ddh();
        ddhVar99.a = "camera.jpeg_data_rotation";
        bf = ddhVar99.f();
        new ddh().a = "camera.debug_lossless_image";
        ddh ddhVar100 = new ddh();
        ddhVar100.a = "test_only_camera_device_disable";
        ddhVar100.c = ope.K(0, 1, 2, 3);
        w = ddhVar100.a();
        ddh ddhVar101 = new ddh();
        ddhVar101.a = "test_only_camera_open_disable";
        ddhVar101.c = ope.K(0, 1, 2, 3);
        x = ddhVar101.a();
        ddh ddhVar102 = new ddh();
        ddhVar102.a = "test_only_camera_id_rear";
        ddhVar102.c = omm.a(orj.g(-1, 9), omv.a);
        y = ddhVar102.a();
        ddh ddhVar103 = new ddh();
        ddhVar103.a = "test_only_camera_id_front";
        ddhVar103.c = omm.a(orj.g(-1, 9), omv.a);
        z = ddhVar103.a();
        ddh ddhVar104 = new ddh();
        ddhVar104.b = "HardwareHelp";
        ddhVar104.a = "open_duration_threshold_for_fallback_millis";
        A = ddhVar104.a();
        ddh ddhVar105 = new ddh();
        ddhVar105.a = "test_only_open_duration_threshold_millis";
        B = ddhVar105.a();
        ddh ddhVar106 = new ddh();
        ddhVar106.a = "camera.thread_throttling";
        bg = ddhVar106.f();
        ddh ddhVar107 = new ddh();
        ddhVar107.b = "HardwareHelp";
        ddhVar107.a = "device_help";
        bh = ddhVar107.f();
        ddh ddhVar108 = new ddh();
        ddhVar108.b = "HardwareHelp";
        ddhVar108.a = "enumeration_failures_before_reboot_threshold";
        C = ddhVar108.a();
        ddh ddhVar109 = new ddh();
        ddhVar109.b = "HardwareHelp";
        ddhVar109.a = "enumeration_failures_after_reboot_threshold";
        D = ddhVar109.a();
        ddh ddhVar110 = new ddh();
        ddhVar110.b = "HardwareHelp";
        ddhVar110.a = "fatal_failures_before_reboot_threshold";
        E = ddhVar110.a();
        ddh ddhVar111 = new ddh();
        ddhVar111.b = "HardwareHelp";
        ddhVar111.a = "fatal_failures_after_reboot_threshold";
        F = ddhVar111.a();
        ddh ddhVar112 = new ddh();
        ddhVar112.a = "fatal_error_tracker_days_to_reset";
        ddhVar112.b = "General";
        G = ddhVar112.a();
        ddh ddhVar113 = new ddh();
        ddhVar113.b = "HardwareHelp";
        ddhVar113.a = "working_camera_fallback_enabled";
        bi = ddhVar113.f();
        new ddh().a = "camera.share_preview_analysis";
        new ddh().a = "test_only_working_camera_fallback_enabled";
        ddh ddhVar114 = new ddh();
        ddhVar114.b = "HardwareHelp";
        ddhVar114.a = "support_link";
        bj = ddhVar114.g();
        new ddh().a = "camera.naruto";
        new ddh().a = "camera.analysis.private";
        new ddh().a = "camera.viewfinder_effect_enabled_photo";
        ddh ddhVar115 = new ddh();
        ddhVar115.a = "camera.viewfinder_effect_disabled_photo";
        bk = ddhVar115.f();
        ddh ddhVar116 = new ddh();
        ddhVar116.a = "camera.viewfinder_effect_disabled_night";
        bl = ddhVar116.f();
        new ddh().a = "camera.crash_on_invalid_meta_data_from_media_store";
        new ddh().a = "camera.mediastorage_crash_on_second_publish";
        ddh ddhVar117 = new ddh();
        ddhVar117.a = "ideal_aov_rad";
        bm = ddhVar117.e();
        ddh ddhVar118 = new ddh();
        ddhVar118.a = "support_viewfinder_double_tap";
        ddhVar118.b = "General";
        bn = ddhVar118.f();
        ddh ddhVar119 = new ddh();
        ddhVar119.a = "enable_survey";
        ddhVar119.b = "Survey";
        new ddh().a = "camera.enable_dogfood_notifications";
        ddh ddhVar120 = new ddh();
        ddhVar120.a = "enable_countdown_indicator";
        bo = ddhVar120.f();
        ddh ddhVar121 = new ddh();
        ddhVar121.a = "enable_mars";
        bp = ddhVar121.f();
        ddh ddhVar122 = new ddh();
        ddhVar122.a = "camera.enable_inapp_update";
        bq = ddhVar122.f();
        new ddh().a = "camera.topshotp";
        new ddh().a = "camera.topshotns";
        new ddh().a = "enable_flounder.RESTART";
        new ddh().a = "enable_flounder_mediapipe";
        ddh ddhVar123 = new ddh();
        ddhVar123.a = "enable_3a_control_reset";
        br = ddhVar123.f();
        new ddh().a = "camera.zoom.debug";
        ddh ddhVar124 = new ddh();
        ddhVar124.a = "camera.zoom.initial_zoom";
        bs = ddhVar124.e();
        ddh ddhVar125 = new ddh();
        ddhVar125.a = "camera.enable_sideline";
        bt = ddhVar125.f();
        new ddh().a = "photosphere_frame_server_api_enabled";
        new ddh().a = "camera.pd_dump";
        new ddh().a = "camera.shot_tracking.crash_when_stuck";
        new ddh().a = "camera.enable_video_test_animation";
        ddh ddhVar126 = new ddh();
        ddhVar126.a = "camera.video_test_animation_renderer_type";
        H = ddhVar126.a();
        new ddh().a = "camera.immersive_cropped_aspect_ratio";
        ddh ddhVar127 = new ddh();
        ddhVar127.a = "camera.hal_capture_status";
        bu = ddhVar127.f();
        new ddh().a = "enable_sensitive_image_rotation";
    }

    /* JADX WARN: Multi-variable type inference failed */
    /* JADX WARN: Type inference failed for: r4v2, types: [boolean, int] */
    public static void a(ddk ddkVar, lzh lzhVar, dei deiVar) {
        ddkVar.s(I, true);
        ddkVar.s(J, true);
        ddkVar.s(L, true);
        ddkVar.q(M, true);
        ddkVar.s(N, true);
        ddkVar.s(O, true);
        ddkVar.t(P, "");
        ddkVar.t(Q, "");
        ddkVar.t(R, "");
        ddkVar.t(S, "");
        ddkVar.u(Z, "camera-feedback@google.com");
        ddkVar.u(aa, "camera-feedback@google.com");
        ddkVar.u(ab, "pixel-dogfood-discuss@google.com");
        ddkVar.o(b, null);
        ddkVar.s(ac, false);
        ddkVar.s(ad, true);
        ddkVar.p(ae);
        ddkVar.o(c, 1);
        ddkVar.o(d, 0);
        ddkVar.s(af, false);
        ddkVar.o(e, 512);
        ddkVar.o(f, 22500000);
        ddkVar.s(ai, true);
        ddkVar.t(aj, "3.6");
        ddg ddgVar = ak;
        boolean z2 = deiVar == dei.RELEASE || deiVar == dei.DOGFOOD;
        ddkVar.s(ddgVar, z2);
        ddkVar.s(al, false);
        ddkVar.o(j, Integer.valueOf((int) TimeUnit.HOURS.toSeconds(8L)));
        ddkVar.o(k, 1800000);
        ddkVar.s(am, true);
        ddkVar.s(an, true);
        ddkVar.s(ao, kcy.a != null);
        ddkVar.p(ap);
        ddkVar.s(aq, false);
        ddkVar.s(ar, false);
        ddkVar.o(l, 5000);
        ddkVar.o(m, -1);
        ddkVar.o(n, -1);
        ddkVar.s(as, false);
        ddkVar.s(at, false);
        ddkVar.s(ax, lzhVar.e);
        boolean z3 = lzhVar.f;
        ddkVar.o(p, 2000);
        ddkVar.s(aE, kda.r != null);
        ddkVar.s(az, false);
        ddkVar.p(aA);
        deiVar.equals(dei.ENG);
        ddkVar.s(aD, true);
        ddkVar.o(q, 30);
        ddkVar.q(aF, true);
        ddkVar.o(r, 2000);
        ddkVar.s(aH, true);
        ddkVar.s(aI, false);
        ddkVar.s(aK, lzhVar.e);
        ddkVar.o(g, -5937);
        ddkVar.q(ag, false);
        ddkVar.o(h, -855643953);
        ddkVar.o(i, -855643953);
        ddkVar.s(ah, true);
        ddkVar.o(s, 2);
        ddkVar.s(aL, false);
        ddkVar.s(aM, false);
        ddkVar.s(aN, true);
        ddkVar.s(aU, true);
        ddkVar.s(aO, false);
        ddkVar.s(aP, false);
        ddkVar.s(aR, false);
        ddkVar.s(aS, false);
        ddkVar.s(aT, true);
        ddkVar.s(K, true);
        ddkVar.s(aV, false);
        ddkVar.s(aW, false);
        ddkVar.s(aX, false);
        ddkVar.s(aQ, true);
        ddkVar.s(aG, false);
        ddkVar.s(aw, true);
        ddkVar.s(aY, false);
        ddkVar.s(aJ, false);
        ddkVar.s(aZ, true);
        ddkVar.s(ba, true);
        ddkVar.o(v, null);
        ddkVar.s(aB, true);
        ddkVar.s(aC, true);
        ddkVar.s(bb, true);
        ddkVar.o(t, 60);
        ddkVar.o(u, 80);
        ddkVar.t(bc, "");
        ddkVar.s(bd, true);
        ddkVar.s(be, true);
        ddkVar.s(bf, true);
        ddkVar.s(T, false);
        ddkVar.s(U, false);
        ddkVar.s(V, true);
        ddkVar.o(a, 150);
        ddkVar.s(W, false);
        ddkVar.o(w, 3);
        ddkVar.o(x, 3);
        ddkVar.o(y, -1);
        ddkVar.o(z, -1);
        ddkVar.s(bk, false);
        ddkVar.s(bl, false);
        ddkVar.s(ddo.c, false);
        ddkVar.o(G, 4);
        ddkVar.o(A, 1000);
        ddkVar.s(bi, false);
        ddkVar.o(B, 0);
        ddkVar.s(bg, false);
        ddkVar.r(bm, Float.valueOf(1.408535f));
        ddkVar.s(bh, false);
        ddkVar.o(C, Integer.MAX_VALUE);
        ddkVar.o(D, Integer.MAX_VALUE);
        ddkVar.o(E, Integer.MAX_VALUE);
        ddkVar.o(F, Integer.MAX_VALUE);
        ddkVar.s(bn, true);
        ddkVar.t(bj, "https://support.google.com/pixelphone/gethelp");
        ddkVar.s(bo, true);
        ddkVar.s(bp, false);
        ddg ddgVar2 = bq;
        deiVar.a(dei.ENG);
        ddkVar.s(ddgVar2, false);
        ddkVar.s(br, Pref.MenuValue("pref_expslideswitch_key"));
        ddkVar.r(bs, Float.valueOf(1.0f));
        ddkVar.s(bt, false);
        ddkVar.s(ay, true);
        ddkVar.s(X, false);
        ddkVar.s(Y, false);
        ddkVar.o(H, 1);
        ddkVar.s(bu, false);
    }
}
