package defpackage;

/* JADX INFO: loaded from: classes.dex */
public final class ddm {
    public static final ddg A;
    public static final ddg B;
    public static final ddg C;
    public static final ddg D;
    public static final ddg E;
    public static final ddg F;
    public static final ddg G;
    public static final ddg H;
    public static final ddg I;
    public static final ddg J;
    public static final ddg K;
    public static final ddg L;
    public static final ddg M;
    public static final ddg N;
    public static final ddg O;
    public static final ddg P;
    public static final ddg Q;
    public static final ddg R;
    public static final ddg S;
    public static final ddg T;
    public static final ddg U;
    public static final ddg V;
    public static final ddg W;
    public static final ddg X;
    public static final ddg XF;
    public static final ddg Y;
    public static final ddg Z;
    public static final ddi a;
    public static final ddg aa;
    public static final ddg ab;
    public static final ddg ac;
    public static final ddg ad;
    public static final ddg ae;
    public static final ddg af;
    public static final ddg ag;
    public static final ddg ah;
    public static final ddg ai;
    public static final ddg aj;
    public static final ddg ak;
    public static final ddg al;
    public static final ddg am;
    public static final ddg an;
    public static final ddg ao;
    public static final ddg ap;
    public static final ddg aq;
    public static final ddg ar;
    public static final ddg as;
    public static final ddg at;
    public static final ddi b;
    public static final ddi c;
    public static final ddi d;
    public static final ddi e;
    public static final ddi f;
    public static final ddi g;
    public static final ddi h;
    public static final ddi i;
    public static final ddi j;
    public static final ddi k;
    public static final ddi l;
    public static final ddi m;
    public static final ddi n;
    public static final ddi o;
    public static final ddi p;
    public static final ddi q;
    public static final ddi r;
    public static final ddi s;
    public static final ddi t;
    public static final ddi u;
    public static final ddi v;
    public static final ddi w;
    public static final ddi x;
    public static final ddg y;
    public static final ddg z;

    static {
        ddh ddhVar = new ddh();
        ddhVar.a = "camera.3a.debug_meta";
        ddhVar.c = ope.K(0, 1, 2, 3);
        a = ddhVar.a();
        ddh ddhVar2 = new ddh();
        ddhVar2.a = "camera.cuttle.motion_ef";
        y = ddhVar2.c();
        ddh ddhVar3 = new ddh();
        ddhVar3.a = "camera.cuttle.motion_metadata";
        z = ddhVar3.f();
        ddh ddhVar4 = new ddh();
        ddhVar4.a = "camera.cuttle.extended";
        A = ddhVar4.f();
        new ddh().a = "camera.force_cuttle.extended";
        new ddh().a = "camera.cuttle.extended.fz.RESTART";
        ddh ddhVar5 = new ddh();
        ddhVar5.a = "camera.cuttle.sky";
        B = ddhVar5.f();
        ddh ddhVar6 = new ddh();
        ddhVar6.a = "camera.cuttle.max_exp_ms";
        C = ddhVar6.e();
        ddh ddhVar7 = new ddh();
        ddhVar7.a = "camera.cuttle.extended_iterable_burst";
        D = ddhVar7.f();
        ddh ddhVar8 = new ddh();
        ddhVar8.a = "camera.cuttle.rerun_fd";
        E = ddhVar8.f();
        ddh ddhVar9 = new ddh();
        ddhVar9.a = "camera.3a_conv";
        F = ddhVar9.f();
        new ddh().a = "camera.extburst.RESTART";
        ddh ddhVar10 = new ddh();
        ddhVar10.a = "gcam.hdrplus_wb_source";
        ddhVar10.c = ope.J(0, 1, 2);
        b = ddhVar10.a();
        ddh ddhVar11 = new ddh();
        ddhVar11.a = "gcam.psaf_frame_count";
        ddhVar11.c = omm.a(orj.g(0, 10), omv.a);
        c = ddhVar11.a();
        ddh ddhVar12 = new ddh();
        ddhVar12.a = "gcam.psaf_exp_time_ms";
        G = ddhVar12.e();
        ddh ddhVar13 = new ddh();
        ddhVar13.a = "gcam.psaf_sb_thresh";
        H = ddhVar13.e();
        ddh ddhVar14 = new ddh();
        ddhVar14.a = "gcam_capture_thread_count";
        d = ddhVar14.a();
        ddh ddhVar15 = new ddh();
        ddhVar15.a = "gcam_merge_thread_count";
        e = ddhVar15.a();
        ddh ddhVar16 = new ddh();
        ddhVar16.a = "gcam_finish_thread_count";
        f = ddhVar16.a();
        ddh ddhVar17 = new ddh();
        ddhVar17.a = "gcam.zsl_buffer_size";
        g = ddhVar17.a();
        ddh ddhVar18 = new ddh();
        ddhVar18.a = "camera.hdr_hvx.RESTART";
        I = ddhVar18.c();
        new ddh().a = "camera.hdr_postview_hvx.RESTART";
        ddh ddhVar19 = new ddh();
        ddhVar19.a = "gcam.max_burst_size";
        h = ddhVar19.a();
        ddh ddhVar20 = new ddh();
        ddhVar20.a = "camera.cuttle.max_burst_size";
        i = ddhVar20.a();
        ddh ddhVar21 = new ddh();
        ddhVar21.a = "camera.p3_available";
        J = ddhVar21.c();
        new ddh().a = "camera.p3_force";
        ddh ddhVar22 = new ddh();
        ddhVar22.a = "camera.shasta_psl";
        K = ddhVar22.f();
        ddh ddhVar23 = new ddh();
        ddhVar23.a = "camera.shasta_zsl";
        L = ddhVar23.f();
        ddh ddhVar24 = new ddh();
        ddhVar24.a = "camera.shasta.frame_retention_ms";
        j = ddhVar24.a();
        new ddh().a = "camera.shasta.force";
        ddh ddhVar25 = new ddh();
        ddhVar25.a = "camera.shasta.factor";
        M = ddhVar25.e();
        ddh ddhVar26 = new ddh();
        ddhVar26.a = "camera.shasta_zsl.burst_size";
        k = ddhVar26.a();
        ddh ddhVar27 = new ddh();
        ddhVar27.a = "camera.shasta_zsl.max_exptime_ms";
        N = ddhVar27.e();
        ddh ddhVar28 = new ddh();
        ddhVar28.a = "SABRE_ALLOWED";
        O = ddhVar28.f();
        new ddh().a = "camera.sabre_force";
        ddh ddhVar29 = new ddh();
        ddhVar29.a = "camera.spatial_rgb_enabled";
        P = ddhVar29.f();
        new ddh().a = "camera.spatial_rgb_force";
        ddh ddhVar30 = new ddh();
        ddhVar30.a = "camera.wiener_force";
        Q = ddhVar30.f();
        new ddh().a = "camera.sabre_unzoomed_all";
        ddh ddhVar31 = new ddh();
        ddhVar31.a = "camera.sabre_unzoomed_tele";
        R = ddhVar31.f();
        ddh ddhVar32 = new ddh();
        ddhVar32.a = "camera.sabre_unzoomed_ns";
        S = ddhVar32.f();
        new ddh().a = "camera.sabre_unzoomed_astro";
        new ddh().a = "camera.slowraw";
        ddh ddhVar33 = new ddh();
        ddhVar33.a = "camera.estrella_login_enabled";
        T = ddhVar33.c();
        new ddh().a = "camera.catfish_enabled";
        ddh ddhVar34 = new ddh();
        ddhVar34.a = "camera.catfish_flash_anim_capture_threshold_ms";
        l = ddhVar34.a();
        new ddh().a = "camera.flash_animation_experiment";
        ddh ddhVar35 = new ddh();
        ddhVar35.a = "camera.flash_anim_fade_in_ms";
        m = ddhVar35.a();
        ddh ddhVar36 = new ddh();
        ddhVar36.a = "camera.flash_anim_fade_out_ms";
        n = ddhVar36.a();
        ddh ddhVar37 = new ddh();
        ddhVar37.a = "camera.flash_anim_max_alpha";
        U = ddhVar37.e();
        ddh ddhVar38 = new ddh();
        ddhVar38.a = "POST_CAPTURE_TEMPORAL_BINNING";
        V = ddhVar38.f();
        new ddh().a = "camera.force_low_light_fps";
        ddh ddhVar39 = new ddh();
        ddhVar39.a = "gcam.zsl_ns";
        W = ddhVar39.f();
        ddh ddhVar40 = new ddh();
        ddhVar40.a = "gcam.zsl_ns.forcedtbfactor";
        o = ddhVar40.a();
        ddh ddhVar41 = new ddh();
        ddhVar41.a = "hdrnet_enabled";
        X = ddhVar41.f();
        ddh ddhVar42 = new ddh();
        ddhVar42.a = "dualev_enabled";
        XF = ddhVar42.f();
        ddh ddhVar43 = new ddh();
        ddhVar43.a = "camera.hdrnet.height";
        p = ddhVar43.a();
        new ddh().a = "camera.hdrnet.hi-res";
        ddh ddhVar44 = new ddh();
        ddhVar44.a = "camera.nonzsl_extended_base_frame_selection";
        Y = ddhVar44.c();
        new ddh().a = "gcam.vf.verbose";
        ddh ddhVar45 = new ddh();
        ddhVar45.a = "gcam.sabre_burst_size";
        q = ddhVar45.a();
        ddh ddhVar46 = new ddh();
        ddhVar46.a = "gcam.temporal_binning_burst_size";
        r = ddhVar46.a();
        ddh ddhVar47 = new ddh();
        ddhVar47.a = "camera.zsl.extended_buffer_factor";
        Z = ddhVar47.e();
        ddh ddhVar48 = new ddh();
        ddhVar48.a = "camera.catshark_enabled.RESTART";
        aa = ddhVar48.f();
        ddh ddhVar49 = new ddh();
        ddhVar49.a = "camera.catshark_cheese";
        ab = ddhVar49.f();
        ddh ddhVar50 = new ddh();
        ddhVar50.a = "camera.catshark_in_threshold";
        ac = ddhVar50.e();
        ddh ddhVar51 = new ddh();
        ddhVar51.a = "camera.catshark_out_threshold";
        ad = ddhVar51.e();
        ddh ddhVar52 = new ddh();
        ddhVar52.a = "camera.catshark_cheese_in_threshold";
        ae = ddhVar52.e();
        ddh ddhVar53 = new ddh();
        ddhVar53.a = "camera.catshark_cheese_out_threshold";
        af = ddhVar53.e();
        ddh ddhVar54 = new ddh();
        ddhVar54.a = "camera.catshark_full_threshold";
        ag = ddhVar54.e();
        ddh ddhVar55 = new ddh();
        ddhVar55.a = "camera.catshark_af";
        ah = ddhVar55.f();
        ddh ddhVar56 = new ddh();
        ddhVar56.a = "camera.catshark_minibar_enabled";
        ai = ddhVar56.f();
        ddh ddhVar57 = new ddh();
        ddhVar57.a = "camera.cuttle.fastaf";
        aj = ddhVar57.f();
        ddh ddhVar58 = new ddh();
        ddhVar58.a = "camera.kepler_enabled";
        ak = ddhVar58.f();
        ddh ddhVar59 = new ddh();
        ddhVar59.a = "camera.kepler_min_frame_count";
        s = ddhVar59.a();
        ddh ddhVar60 = new ddh();
        ddhVar60.a = "camera.kepler_merge_frame_count";
        t = ddhVar60.a();
        ddh ddhVar61 = new ddh();
        ddhVar61.a = "camera.kepler_capture_threshold_ms";
        u = ddhVar61.a();
        ddh ddhVar62 = new ddh();
        ddhVar62.a = "camera.kepler_stream_enabled";
        al = ddhVar62.f();
        new ddh().a = "camera.kepler_hevc_enabled";
        ddh ddhVar63 = new ddh();
        ddhVar63.a = "camera.kepler_frame_duration_ms";
        v = ddhVar63.a();
        new ddh().a = "camera.kepler_micro";
        ddh ddhVar64 = new ddh();
        ddhVar64.a = "camera.disable_hdrplus_postview";
        am = ddhVar64.f();
        ddh ddhVar65 = new ddh();
        ddhVar65.a = "camera.cuttle.enable_timeout";
        an = ddhVar65.f();
        ddh ddhVar66 = new ddh();
        ddhVar66.a = "camera.cuttle.custom_timeout_ms";
        w = ddhVar66.a();
        ddh ddhVar67 = new ddh();
        ddhVar67.a = "camera.hdr_plus_torch_thermal_throttling";
        ao = ddhVar67.f();
        ddh ddhVar68 = new ddh();
        ddhVar68.a = "camera.falcon_enabled";
        ap = ddhVar68.f();
        new ddh().a = "camera.falcon_annotate";
        new ddh().a = "camera.falcon_save_original";
        new ddh().a = "camera.falcon_process_original";
        new ddh().a = "camera.falcon_save_secondary";
        ddh ddhVar69 = new ddh();
        ddhVar69.a = "camera.falcon_power_hint";
        aq = ddhVar69.f();
        new ddh().a = "camera.falcon_always_on";
        new ddh().a = "camera.falcon_force_fusion";
        new ddh().a = "camera.falcon_ahwb";
        new ddh().a = "camera.falcon_standby";
        ddh ddhVar70 = new ddh();
        ddhVar70.a = "camera.falcon_flush_sample_count";
        x = ddhVar70.a();
        ddh ddhVar71 = new ddh();
        ddhVar71.a = "camera.gpu_sampled_image";
        ar = ddhVar71.f();
        new ddh().a = "camera.include_ultra_short_frame";
        ddh ddhVar72 = new ddh();
        ddhVar72.a = "gcam.metering.recompute_ae";
        as = ddhVar72.f();
        ddh ddhVar73 = new ddh();
        ddhVar73.a = "gcam.pb_enabled";
        at = ddhVar73.f();
    }
}
