package defpackage;

/* JADX INFO: loaded from: classes.dex */
public final class ddp {
    public static final ddi a;
    public static final ddi b;
    public static final ddi c;
    public static final ddg d;
    public static final ddg e;
    public static final ddg f;
    public static final ddg g;
    public static final ddg h;
    public static final ddg i;
    public static final ddg j;
    public static final ddg k;
    public static final ddg l;
    public static final ddg m;
    public static final ddg n;
    public static final ddg o;
    public static final ddg p;
    public static final ddg q;
    public static final ddg r;
    public static final ddg s;
    public static final ddg t;
    public static final ddg u;
    public static final ddg v;
    public static final ddg w;
    public static final ddg x;
    public static final ddg y;
    public static final ddg z;

    static {
        ddh ddhVar = new ddh();
        ddhVar.a = "camera.enable_lenslite";
        d = ddhVar.f();
        ddh ddhVar2 = new ddh();
        ddhVar2.b = "Lens";
        ddhVar2.a = "enable_lenslite";
        e = ddhVar2.f();
        ddh ddhVar3 = new ddh();
        ddhVar3.b = "Lens";
        ddhVar3.a = "force_cpu_processing";
        f = ddhVar3.f();
        new ddh().a = "camera.lenslite.force_cpu_processing";
        ddh ddhVar4 = new ddh();
        ddhVar4.a = "camera.lenslite.enable_text_wifi_credentials";
        g = ddhVar4.f();
        ddh ddhVar5 = new ddh();
        ddhVar5.a = "camera.lenslite.enable_document_scanning";
        h = ddhVar5.f();
        ddh ddhVar6 = new ddh();
        ddhVar6.a = "camera.lenslite.enable_lightweight_suggestions";
        i = ddhVar6.f();
        ddh ddhVar7 = new ddh();
        ddhVar7.a = "camera.lenslite.enable_foreign_contact_recognition";
        j = ddhVar7.f();
        new ddh().a = "camera.lenslite.force_enable_capabilities";
        ddh ddhVar8 = new ddh();
        ddhVar8.a = "camera.lenslite.enable_dynamic_loading";
        k = ddhVar8.f();
        ddh ddhVar9 = new ddh();
        ddhVar9.a = "dynamic_loading_from_playground";
        l = ddhVar9.f();
        ddh ddhVar10 = new ddh();
        ddhVar10.a = "stop_pipeline_on_pause";
        ddhVar10.b = "Lens";
        m = ddhVar10.f();
        ddh ddhVar11 = new ddh();
        ddhVar11.a = "camera.lenslite.trivial_feature_enabled_bits";
        a = ddhVar11.a();
        ddh ddhVar12 = new ddh();
        ddhVar12.a = "camera.lenslite.enable_logging";
        n = ddhVar12.f();
        ddh ddhVar13 = new ddh();
        ddhVar13.a = "camera.lenslite.ornament_vr";
        o = ddhVar13.f();
        ddh ddhVar14 = new ddh();
        ddhVar14.a = "fast_scan_enabled";
        p = ddhVar14.f();
        ddh ddhVar15 = new ddh();
        ddhVar15.a = "camera_vision_kit_enabled";
        q = ddhVar15.f();
        ddh ddhVar16 = new ddh();
        ddhVar16.b = "Lens";
        ddhVar16.a = "camera_vision_kit";
        r = ddhVar16.f();
        ddh ddhVar17 = new ddh();
        ddhVar17.a = "translate_edu";
        s = ddhVar17.f();
        ddh ddhVar18 = new ddh();
        ddhVar18.a = "fast_scan_fps";
        ddhVar18.c = ope.M(1, 2, 3, 4, 10, 15, 30);
        b = ddhVar18.a();
        ddh ddhVar19 = new ddh();
        ddhVar19.a = "fast_scan_pass_through";
        t = ddhVar19.f();
        ddh ddhVar20 = new ddh();
        ddhVar20.b = "Lens";
        ddhVar20.a = "fast_scan_pass_through_interval";
        u = ddhVar20.e();
        ddh ddhVar21 = new ddh();
        ddhVar21.a = "cvk_frame_supply_fps";
        ddhVar21.c = ope.L(4, 10, 15, 30, 60);
        c = ddhVar21.a();
        ddh ddhVar22 = new ddh();
        ddhVar22.a = "scene_detection_enabled";
        v = ddhVar22.f();
        ddh ddhVar23 = new ddh();
        ddhVar23.a = "content_detection_enabled";
        w = ddhVar23.f();
        ddh ddhVar24 = new ddh();
        ddhVar24.a = "scan_document_enabled";
        x = ddhVar24.f();
        ddh ddhVar25 = new ddh();
        ddhVar25.a = "camera_vision_kit_acceleration_enabled";
        y = ddhVar25.f();
        ddh ddhVar26 = new ddh();
        ddhVar26.b = "Lens";
        ddhVar26.a = "arcore_fast_scan_compatible";
        z = ddhVar26.f();
        new ddh().a = "test_only_arcore_fast_scan_compatible";
        new ddh().a = "vkp_low_energy_enabled";
        new ddh().a = "cvk_debug_mode";
    }
}
