package defpackage;

/* JADX INFO: loaded from: classes.dex */
public final class ddr {
    public static final ddi a;
    public static final ddi b;
    public static final ddg c;
    public static final ddg d;
    public static final ddg e;
    public static final ddg f;
    public static final ddg g;
    public static final ddg h;
    public static final ddg i;
    public static final ddg j;
    public static final ddg k;
    public static final ddg l;
    public static final ddg m;
    public static final ddg n;
    public static final ddg o;
    public static final ddg p;
    public static final ddg q;
    public static final ddg r;
    public static final ddg s;
    public static final ddg t;
    public static final ddg u;
    public static final ddg v;
    public static final ddg w;
    public static final ddg x;
    public static final ddg y;
    public static final ddg z;

    static {
        new ddh().a = "camera.micro_datacoll";
        new ddh().a = "camera.micro_fragmented";
        new ddh().a = "camera.enable_jpgcheck";
        new ddh().a = "camera.micro_cam_pose";
        new ddh().a = "camera.micro_creation";
        new ddh().a = "camera.micro_no_gyro";
        new ddh().a = "camera.enable_micro_he";
        new ddh().a = "camera.micro_longp_hires";
        ddh ddhVar = new ddh();
        ddhVar.a = "camera.micro_longp_mp4";
        c = ddhVar.c();
        new ddh().a = "camera.micro_longp_lj";
        ddh ddhVar2 = new ddh();
        ddhVar2.a = "camera.micro_longp_md";
        d = ddhVar2.f();
        new ddh().a = "camera.micro_longp_pre_audio";
        ddh ddhVar3 = new ddh();
        ddhVar3.a = "camera.micro_motion";
        e = ddhVar3.c();
        new ddh().a = "camera.micro_profile";
        ddh ddhVar4 = new ddh();
        ddhVar4.a = "camera.micro_tone_map";
        f = ddhVar4.d();
        ddh ddhVar5 = new ddh();
        ddhVar5.a = "camera.micro_tooltip";
        g = ddhVar5.c();
        new ddh().a = "camera.micro_trimtoast";
        ddh ddhVar6 = new ddh();
        ddhVar6.a = "camera.enable_micro";
        h = ddhVar6.f();
        ddh ddhVar7 = new ddh();
        ddhVar7.a = "micro_video_supported";
        i = ddhVar7.f();
        ddh ddhVar8 = new ddh();
        ddhVar8.a = "camera.micro_prestab";
        j = ddhVar8.f();
        ddh ddhVar9 = new ddh();
        ddhVar9.a = "camera.micro_v2_format";
        k = ddhVar9.f();
        new ddh().a = "camera.micro_longp_v2";
        new ddh().a = "camera.mv_dump_yuv";
        new ddh().a = "camera.mv_verbose";
        ddh ddhVar10 = new ddh();
        ddhVar10.a = "camera.micro_gcamux";
        l = ddhVar10.f();
        new ddh().a = "camera.micro_stab_locked";
        new ddh().a = "camera.micro_render_stab_mesh";
        ddh ddhVar11 = new ddh();
        ddhVar11.a = "camera.micro_longp_slide";
        m = ddhVar11.f();
        ddh ddhVar12 = new ddh();
        ddhVar12.a = "camera.longp_topshot_indicator";
        n = ddhVar12.f();
        ddh ddhVar13 = new ddh();
        ddhVar13.a = "camera.longp_zoom_lock";
        o = ddhVar13.f();
        ddh ddhVar14 = new ddh();
        ddhVar14.a = "camera.longp_top_shot_animation";
        a = ddhVar14.a();
        new ddh().a = "camera.longp_topshot_indicator_enable_hw_layer_type";
        new ddh().a = "camera.micro_debug_trimmer";
        new ddh().a = "camera.micro_overlay_metrics";
        ddh ddhVar15 = new ddh();
        ddhVar15.a = "camera.micro_bottom_sheet";
        p = ddhVar15.f();
        ddh ddhVar16 = new ddh();
        ddhVar16.a = "camera.micro_ls_always_prestab";
        q = ddhVar16.f();
        ddh ddhVar17 = new ddh();
        ddhVar17.a = "camera.micro_longp_help";
        r = ddhVar17.f();
        ddh ddhVar18 = new ddh();
        ddhVar18.a = "camera.longp_topshot_notification";
        s = ddhVar18.f();
        new ddh().a = "camera.micro_dynamic_i";
        new ddh().a = "camera.direct_encode";
        ddh ddhVar19 = new ddh();
        ddhVar19.a = "camera.micro_full_color_range";
        t = ddhVar19.f();
        ddh ddhVar20 = new ddh();
        ddhVar20.a = "camera.micro_newtrimmer";
        u = ddhVar20.f();
        ddh ddhVar21 = new ddh();
        ddhVar21.a = "camera.micro_early_ls";
        v = ddhVar21.f();
        ddh ddhVar22 = new ddh();
        ddhVar22.a = "camera.micro_ls_cancel";
        w = ddhVar22.f();
        ddh ddhVar23 = new ddh();
        ddhVar23.a = "camera.r_pending_vids";
        x = ddhVar23.f();
        ddh ddhVar24 = new ddh();
        ddhVar24.a = "camera.check_pending_vids";
        y = ddhVar24.f();
        ddh ddhVar25 = new ddh();
        ddhVar25.a = "camera.micro_ls_cthreshold";
        b = ddhVar25.a();
        new ddh().a = "camera.ls_on_mash";
        ddh ddhVar26 = new ddh();
        ddhVar26.a = "camera.mv_no_double_close";
        z = ddhVar26.f();
    }

    public static void a(ddk ddkVar, dei deiVar) {
        deiVar.b(dei.ENG);
        ddkVar.p(c);
        ddkVar.s(d, true);
        ddkVar.p(e);
        ddkVar.q(f, true);
        ddkVar.p(g);
        ddkVar.s(i, true);
        ddkVar.s(h, true);
        ddkVar.s(j, false);
        ddkVar.s(k, true);
        ddkVar.s(l, true);
        ddkVar.s(m, true);
        ddkVar.s(o, true);
        ddkVar.s(n, true);
        ddkVar.s(q, false);
        ddkVar.s(r, true);
        ddkVar.s(s, true);
        ddkVar.s(t, false);
        ddkVar.s(u, true);
        ddkVar.s(p, true);
        ddkVar.s(v, true);
        ddkVar.s(w, true);
        ddkVar.s(x, true);
        ddkVar.s(y, true);
        ddkVar.o(b, 800);
        ddkVar.o(a, 2);
        ddkVar.s(z, true);
    }
}
