package defpackage;

/* JADX INFO: loaded from: classes.dex */
public final class dds {
    public static final ddg A;
    public static final ddg B;
    public static final ddg C;
    public static final ddg D;
    public static final ddg E;
    public static final ddg F;
    public static final ddg G;
    public static final ddg H;
    public static final ddg I;
    public static final ddg J;
    public static final ddg K;
    public static final ddg L;
    public static final ddg M;
    public static final ddg N;
    public static final ddg O;
    public static final ddg P;
    public static final ddg Q;
    public static final ddg R;
    public static final ddg S;
    public static final ddg T;
    public static final ddg U;
    public static final ddg V;
    public static final ddg a;
    public static final ddg b;
    public static final ddg c;
    public static final ddg d;
    public static final ddg e;
    public static final ddg f;
    public static final ddg g;
    public static final ddg h;
    public static final ddg i;
    public static final ddg j;
    public static final ddg k;
    public static final ddg l;
    public static final ddg m;
    public static final ddg n;
    public static final ddg o;
    public static final ddg p;
    public static final ddg q;
    public static final ddg r;
    public static final ddg s;
    public static final ddg t;
    public static final ddg u;
    public static final ddg v;
    public static final ddg w;
    public static final ddg x;
    public static final ddg y;
    public static final ddg z;

    static {
        ddh ddhVar = new ddh();
        ddhVar.b = "Topshot";
        ddhVar.a = "camera_mts_aesthetic";
        a = ddhVar.f();
        ddh ddhVar2 = new ddh();
        ddhVar2.b = "Topshot";
        ddhVar2.a = "camera_mts_actions_front";
        b = ddhVar2.f();
        ddh ddhVar3 = new ddh();
        ddhVar3.b = "Topshot";
        ddhVar3.a = "camera_mts_actions_back";
        c = ddhVar3.f();
        ddh ddhVar4 = new ddh();
        ddhVar4.b = "Topshot";
        ddhVar4.a = "camera_mts_face_interactions";
        d = ddhVar4.f();
        ddh ddhVar5 = new ddh();
        ddhVar5.a = "camera.mts_accel_faces_front";
        e = ddhVar5.f();
        ddh ddhVar6 = new ddh();
        ddhVar6.a = "camera.mts_accel_faces_back";
        f = ddhVar6.f();
        ddh ddhVar7 = new ddh();
        ddhVar7.a = "camera.mts_accel_action_front";
        g = ddhVar7.f();
        ddh ddhVar8 = new ddh();
        ddhVar8.a = "camera.mts_accel_action_back";
        h = ddhVar8.f();
        ddh ddhVar9 = new ddh();
        ddhVar9.a = "camera.mts_smartcapturenet_2";
        i = ddhVar9.f();
        ddh ddhVar10 = new ddh();
        ddhVar10.a = "camera.mts_pose";
        j = ddhVar10.f();
        ddh ddhVar11 = new ddh();
        ddhVar11.a = "camera.mts_pose_and_pet";
        k = ddhVar11.f();
        ddh ddhVar12 = new ddh();
        ddhVar12.a = "camera.mts_sc_accel_tpu";
        l = ddhVar12.f();
        ddh ddhVar13 = new ddh();
        ddhVar13.a = "camera.mts_4k";
        m = ddhVar13.f();
        ddh ddhVar14 = new ddh();
        ddhVar14.a = "camera.mts_ls_dupe_last";
        n = ddhVar14.f();
        ddh ddhVar15 = new ddh();
        ddhVar15.a = "camera.mts_ts_ls_dupe_last";
        o = ddhVar15.f();
        new ddh().a = "camera.mts_fc_extraction";
        new ddh().a = "camera.mts_smart_zoom";
        new ddh().a = "camera.mts_scoring_dbg";
        ddh ddhVar16 = new ddh();
        ddhVar16.a = "camera.mts_postview";
        p = ddhVar16.c();
        ddh ddhVar17 = new ddh();
        ddhVar17.a = "camera.mts_fast_hdr";
        q = ddhVar17.f();
        new ddh().a = "camera.mts_fast_de_ts";
        ddh ddhVar18 = new ddh();
        ddhVar18.a = "camera.mts_fast_de_ls";
        r = ddhVar18.f();
        new ddh().a = "camera.mts_ts_de_d2x";
        ddh ddhVar19 = new ddh();
        ddhVar19.a = "camera.mts_ls_de_d2x";
        s = ddhVar19.f();
        ddh ddhVar20 = new ddh();
        ddhVar20.b = "Topshot";
        ddhVar20.a = "mts_ls_de_d2x";
        t = ddhVar20.f();
        new ddh().a = "camera.mts_alt_w_main";
        ddh ddhVar21 = new ddh();
        ddhVar21.b = "Topshot";
        ddhVar21.a = "mts_max_alt_1";
        u = ddhVar21.f();
        ddh ddhVar22 = new ddh();
        ddhVar22.a = "camera.mts_max_alt_1";
        v = ddhVar22.f();
        ddh ddhVar23 = new ddh();
        ddhVar23.b = "Topshot";
        ddhVar23.a = "camera_mts_lowlight_or_zoom";
        w = ddhVar23.f();
        ddh ddhVar24 = new ddh();
        ddhVar24.a = "camera.mts_postproc";
        x = ddhVar24.f();
        ddh ddhVar25 = new ddh();
        ddhVar25.a = "camera.mts_gpu";
        y = ddhVar25.f();
        ddh ddhVar26 = new ddh();
        ddhVar26.a = "camera.mts_hw_enc_w";
        z = ddhVar26.f();
        ddh ddhVar27 = new ddh();
        ddhVar27.b = "Topshot";
        ddhVar27.a = "mts_face_diversity";
        A = ddhVar27.f();
        ddh ddhVar28 = new ddh();
        ddhVar28.a = "camera.mts_face_diversity";
        B = ddhVar28.f();
        ddh ddhVar29 = new ddh();
        ddhVar29.b = "Topshot";
        ddhVar29.a = "mts_aesthetic_diversity";
        C = ddhVar29.f();
        ddh ddhVar30 = new ddh();
        ddhVar30.a = "camera.mts_aesthetic_diversity";
        D = ddhVar30.f();
        ddh ddhVar31 = new ddh();
        ddhVar31.b = "Topshot";
        ddhVar31.a = "mts_long_shot_diversity";
        E = ddhVar31.f();
        ddh ddhVar32 = new ddh();
        ddhVar32.a = "camera.mts_long_shot_diversity";
        F = ddhVar32.f();
        ddh ddhVar33 = new ddh();
        ddhVar33.a = "camera.mts_nima_aesthetic_tpu";
        G = ddhVar33.f();
        ddh ddhVar34 = new ddh();
        ddhVar34.a = "camera.mts_enable_nima_v2";
        H = ddhVar34.f();
        ddh ddhVar35 = new ddh();
        ddhVar35.a = "camera.mts_motion_photo_threshold";
        I = ddhVar35.f();
        ddh ddhVar36 = new ddh();
        ddhVar36.a = "camera.mts_durfix_ls";
        J = ddhVar36.f();
        ddh ddhVar37 = new ddh();
        ddhVar37.a = "camera.mts_durfix_ts";
        K = ddhVar37.f();
        ddh ddhVar38 = new ddh();
        ddhVar38.a = "camera.mts_new_topshot_weight";
        L = ddhVar38.f();
        ddh ddhVar39 = new ddh();
        ddhVar39.a = "camera.mts_wait_ef";
        M = ddhVar39.f();
        new ddh().a = "camera.mts_full_res";
        new ddh().a = "camera.mts_full_br";
        ddh ddhVar40 = new ddh();
        ddhVar40.a = "camera.mts_full_res_ls";
        N = ddhVar40.f();
        ddh ddhVar41 = new ddh();
        ddhVar41.a = "camera.mts_full_br_ls";
        O = ddhVar41.f();
        ddh ddhVar42 = new ddh();
        ddhVar42.a = "camera.mts_full_color_range";
        P = ddhVar42.f();
        ddh ddhVar43 = new ddh();
        ddhVar43.a = "camera.mts_func_encoder";
        Q = ddhVar43.f();
        ddh ddhVar44 = new ddh();
        ddhVar44.a = "camera.mts_prewarm";
        R = ddhVar44.c();
        ddh ddhVar45 = new ddh();
        ddhVar45.a = "camera.mts_gpu_yuv";
        S = ddhVar45.f();
        new ddh().a = "camera.mts_early_first_alt";
        ddh ddhVar46 = new ddh();
        ddhVar46.a = "camera.mts_newscore";
        T = ddhVar46.f();
        ddh ddhVar47 = new ddh();
        ddhVar47.a = "camera.longshot_xtra_frames";
        U = ddhVar47.f();
        ddh ddhVar48 = new ddh();
        ddhVar48.a = "camera.longshot_lazy_proc";
        V = ddhVar48.f();
        new ddh().a = "camera.mts_direct_encode";
        new ddh().a = "camera.mts_lite";
    }
}
