package defpackage;

/* JADX INFO: loaded from: classes.dex */
public final class ddu {
    public static final ddi a;
    public static final ddi b;
    public static final ddi c;
    public static final ddi d;
    public static final ddi e;
    public static final ddi f;
    public static final ddi g;
    public static final ddi h;
    public static final ddg i;
    public static final ddg j;
    public static final ddg k;
    public static final ddg l;
    public static final ddg m;
    public static final ddg n;
    public static final ddg o;
    public static final ddg p;
    public static final ddg q;
    public static final ddg r;
    public static final ddg s;
    public static final ddg t;
    public static final ddg u;
    public static final ddg v;

    static {
        ddh ddhVar = new ddh();
        ddhVar.a = "face_detect_mode_use_extended";
        i = ddhVar.f();
        ddh ddhVar2 = new ddh();
        ddhVar2.a = "flash_intensity_for_photo_modes";
        a = ddhVar2.a();
        ddh ddhVar3 = new ddh();
        ddhVar3.a = "flash_intensity_for_photo_modes_enabled";
        j = ddhVar3.f();
        ddh ddhVar4 = new ddh();
        ddhVar4.a = "global_imagereader_ticket_limit";
        ddhVar4.a();
        ddh ddhVar5 = new ddh();
        ddhVar5.a = "max_hdr_plus_imagereader_image_count";
        b = ddhVar5.a();
        ddh ddhVar6 = new ddh();
        ddhVar6.a = "max_hdr_plus_burst_frame_count";
        c = ddhVar6.a();
        ddh ddhVar7 = new ddh();
        ddhVar7.a = "max_imagereader_image_count";
        d = ddhVar7.a();
        ddh ddhVar8 = new ddh();
        ddhVar8.a = "pd_image_format_is_raw_depth";
        k = ddhVar8.f();
        ddh ddhVar9 = new ddh();
        ddhVar9.a = "pd_image_format_is_raw_depth10";
        l = ddhVar9.f();
        new ddh().a = "camera.auto_hdrp_conf";
        new ddh().a = "camera.hdrp_conf";
        ddh ddhVar10 = new ddh();
        ddhVar10.a = "camera.f_tuning";
        ddhVar10.c = ope.J(0, 1, 2);
        e = ddhVar10.a();
        ddh ddhVar11 = new ddh();
        ddhVar11.a = "bgae.enabled";
        m = ddhVar11.c();
        ddh ddhVar12 = new ddh();
        ddhVar12.a = "gcam.sm.denom";
        f = ddhVar12.a();
        ddh ddhVar13 = new ddh();
        ddhVar13.a = "gcam.sm.denom_night";
        g = ddhVar13.a();
        ddh ddhVar14 = new ddh();
        ddhVar14.a = "gcam.sm.denom_night_limited";
        h = ddhVar14.a();
        ddh ddhVar15 = new ddh();
        ddhVar15.a = "gcam.sm.enabled";
        n = ddhVar15.f();
        ddh ddhVar16 = new ddh();
        ddhVar16.a = "gcam.sm.log";
        o = ddhVar16.f();
        ddh ddhVar17 = new ddh();
        ddhVar17.a = "gcam.debug";
        p = ddhVar17.f();
        ddh ddhVar18 = new ddh();
        ddhVar18.a = "camera.hwhdr_intent";
        q = ddhVar18.f();
        new ddh().a = "camera.hwhdr_inapp";
        ddh ddhVar19 = new ddh();
        ddhVar19.a = "camera.raw_mode";
        r = ddhVar19.f();
        ddh ddhVar20 = new ddh();
        ddhVar20.a = "portrait_use_pd";
        s = ddhVar20.f();
        ddh ddhVar21 = new ddh();
        ddhVar21.a = "portrait_use_stereo";
        t = ddhVar21.f();
        ddh ddhVar22 = new ddh();
        ddhVar22.a = "portrait_use_ml";
        u = ddhVar22.f();
        ddh ddhVar23 = new ddh();
        ddhVar23.a = "simultaneous_af_ae_trigger_supported";
        v = ddhVar23.f();
    }
}
