package defpackage;

/* JADX INFO: loaded from: classes.dex */
public final class ddx {
    public static final ddg A;
    public static final ddg B;
    public static final ddg C;
    public static final ddg D;
    public static final ddg E;
    public static final ddg F;
    public static final ddg G;
    public static final ddg H;
    public static final ddg I;
    public static final ddi a;
    public static final ddi b;
    public static final ddi c;
    public static final ddi d;
    public static final ddi e;
    public static final ddg f;
    public static final ddg g;
    public static final ddg h;
    public static final ddg i;
    public static final ddg j;
    public static final ddg k;
    public static final ddg l;
    public static final ddg m;
    public static final ddg n;
    public static final ddg o;
    public static final ddg p;
    public static final ddg q;
    public static final ddg r;
    public static final ddg s;
    public static final ddg sh;
    public static final ddg t;
    public static final ddg u;
    public static final ddg v;
    public static final ddg w;
    public static final ddg x;
    public static final ddg y;
    public static final ddg z;

    static {
        ddh ddhVar = new ddh();
        ddhVar.a = "camera.gouda.depthdata";
        f = ddhVar.f();
        ddh ddhVar2 = new ddh();
        ddhVar2.a = "gouda_default_zoom_factor_back";
        g = ddhVar2.e();
        ddh ddhVar3 = new ddh();
        ddhVar3.a = "gouda_doubletap_zoom_factor";
        h = ddhVar3.e();
        new ddh().a = "gouda_use_default_zoom_factor_front_for_test";
        ddh ddhVar4 = new ddh();
        ddhVar4.a = "gouda_default_zoom_factor_front_for_test";
        i = ddhVar4.e();
        ddh ddhVar5 = new ddh();
        ddhVar5.a = "max_gouda_inflight_shots";
        a = ddhVar5.a();
        ddh ddhVar6 = new ddh();
        ddhVar6.a = "portrait_availability";
        j = ddhVar6.f();
        ddh ddhVar7 = new ddh();
        ddhVar7.a = "camera.gouda_debug_img";
        k = ddhVar7.f();
        ddh ddhVar8 = new ddh();
        ddhVar8.a = "camera.gouda.raw";
        l = ddhVar8.f();
        ddh ddhVar9 = new ddh();
        ddhVar9.a = "camera.gouda_sec_img";
        m = ddhVar9.f();
        ddh ddhVar10 = new ddh();
        ddhVar10.a = "segmenter_force_cpu_inference";
        n = ddhVar10.f();
        ddh ddhVar11 = new ddh();
        ddhVar11.a = "segmenter_allow_fp16_processing";
        o = ddhVar11.f();
        ddh ddhVar12 = new ddh();
        ddhVar12.a = "segmenter_allow_texture_type";
        p = ddhVar12.f();
        ddh ddhVar13 = new ddh();
        ddhVar13.a = "camera.gouda.cl_seg";
        q = ddhVar13.f();
        ddh ddhVar14 = new ddh();
        ddhVar14.a = "segmenter_use_darwinn_tpu_delegate";
        r = ddhVar14.f();
        ddh ddhVar15 = new ddh();
        ddhVar15.a = "camera.gouda.matting_enabled";
        s = ddhVar15.f();
        ddh ddhVar16 = new ddh();
        ddhVar16.a = "camera.gouda.firefly_cpu";
        t = ddhVar16.f();
        ddh ddhVar17 = new ddh();
        ddhVar17.a = "camera.gouda.firefly_xeno_jet_cl";
        u = ddhVar17.f();
        ddh ddhVar18 = new ddh();
        ddhVar18.a = "camera.gouda.depth_use_opencl";
        v = ddhVar18.f();
        ddh ddhVar19 = new ddh();
        ddhVar19.a = "camera.gouda.stdepth";
        w = ddhVar19.f();
        ddh ddhVar20 = new ddh();
        ddhVar20.a = "camera.gouda.primary_raw";
        x = ddhVar20.f();
        ddh ddhVar21 = new ddh();
        ddhVar21.a = "camera.gouda.allow_raw_blur_front";
        y = ddhVar21.f();
        ddh ddhVar22 = new ddh();
        ddhVar22.a = "camera.gouda.allow_raw_blur_rear";
        z = ddhVar22.f();
        ddh ddhVar23 = new ddh();
        ddhVar23.a = "camera.gouda.use_dynamic_depth";
        A = ddhVar23.f();
        ddh ddhVar24 = new ddh();
        ddhVar24.a = "camera.gouda.firefly_enabled";
        B = ddhVar24.f();
        ddh ddhVar25 = new ddh();
        ddhVar25.a = "camera.gouda.shasta_zsl";
        C = ddhVar25.f();
        ddh ddhVar26 = new ddh();
        ddhVar26.a = "camera.gouda.spotlight_enhance";
        D = ddhVar26.f();
        ddh ddhVar27 = new ddh();
        ddhVar27.a = "camera.gouda.spotlight_enhance_v2";
        E = ddhVar27.f();
        new ddh().a = "portrait_output_use_gpu_resampling";
        ddh ddhVar28 = new ddh();
        ddhVar28.a = "camera.gouda.single_output";
        F = ddhVar28.f();
        ddh ddhVar29 = new ddh();
        ddhVar29.a = "portrait_power_boost_duration_ms";
        b = ddhVar29.a();
        ddh ddhVar30 = new ddh();
        ddhVar30.a = "camera.gouda.secondary_raw_width";
        c = ddhVar30.a();
        ddh ddhVar31 = new ddh();
        ddhVar31.a = "camera.gouda.secondary_raw_height";
        d = ddhVar31.a();
        ddh ddhVar32 = new ddh();
        ddhVar32.a = "camera.gouda.secondary_row_start";
        e = ddhVar32.a();
        ddh ddhVar33 = new ddh();
        ddhVar33.a = "camera.gouda.max_zoom";
        G = ddhVar33.e();
        ddh ddhVar34 = new ddh();
        ddhVar34.a = "camera.gouda.allow_widest_front";
        H = ddhVar34.f();
        ddh ddhVar35 = new ddh();
        ddhVar35.a = "camera.gouda.max_zoom_override";
        I = ddhVar35.f();
        ddh ddhVar36 = new ddh();
        ddhVar36.a = "camera.gouda.object_portrait";
        sh = ddhVar36.f();
    }
}
