package defpackage;

import com.google.android.apps.camera.ui.layout.GcaLayout;
import com.google.android.apps.camera.ui.views.MainActivityLayout;
import java.util.List;
import java.util.concurrent.atomic.AtomicReference;

/* JADX INFO: loaded from: classes.dex */
public final class evc implements etk {
    public qkg A;
    public qkg B;
    public qkg C;
    public qkg D;
    public qkg E;
    public qkg F;
    public qkg G;
    public qkg H;
    public qkg I;
    public qkg J;
    public qkg K;
    public qkg L;
    public qkg M;
    public qkg N;
    public qkg O;
    public qkg P;
    public qkg Q;
    public qkg R;
    public qkg S;
    public final qkg T;
    public final qkg U;
    public final qkg V;
    public final qkg W;
    public final qkg X;
    public final qkg Y;
    public final qkg Z;
    public final emb a;
    public final qkg aA;
    public final qkg aB;
    public final qkg aC;
    public final qkg aD;
    public final qkg aE;
    public final qkg aF;
    public final qkg aG;
    public final qkg aH;
    public final qkg aI;
    public final qkg aJ;
    public final qkg aK;
    public final qkg aL;
    public final qkg aM;
    public final qkg aN;
    public final qkg aO;
    public final qkg aP;
    public final qkg aQ;
    public final qkg aR;
    public final qkg aS;
    public final qkg aT;
    public final qkg aU;
    public final qkg aV;
    public final qkg aW;
    public final qkg aX;
    public final qkg aY;
    public final qkg aZ;
    public final qkg aa;
    public final qkg ab;
    public final qkg ac;
    public final qkg ad;
    public final qkg ae;
    public final qkg af;
    public final qkg ag;
    public final qkg ah;
    public final qkg ai;
    public final qkg aj;
    public final qkg ak;
    public final qkg al;
    public final qkg am;
    public final qkg an;
    public final qkg ao;
    public final qkg ap;
    public final qkg aq;
    public final qkg ar;
    public final qkg as;
    public final qkg at;
    public final qkg au;
    public final qkg av;
    public final qkg aw;
    public final qkg ax;
    public final qkg ay;
    public final qkg az;
    public final ewb b;
    private qkg bA;
    private qkg bB;
    private qkg bC;
    private qkg bD;
    private qkg bE;
    private qkg bF;
    private qkg bG;
    private qkg bH;
    private qkg bI;
    private qkg bJ;
    private qkg bK;
    private qkg bL;
    private qkg bM;
    private qkg bN;
    private qkg bO;
    private qkg bP;
    private qkg bQ;
    private qkg bR;
    private qkg bS;
    private qkg bT;
    private qkg bU;
    private qkg bV;
    private qkg bW;
    private qkg bX;
    private qkg bY;
    private qkg bZ;
    public final qkg ba;
    public final qkg bb;
    public final qkg bc;
    public final qkg bd;
    public final qkg be;
    public final qkg bf;
    public final qkg bg;
    public final qkg bh;
    public final qkg bi;
    public final qkg bj;
    public final qkg bk;
    public final qkg bl;
    public final qkg bm;
    public final qkg bn;
    private final ete bo;
    private qkg bp;
    private qkg bq;
    private qkg br;
    private qkg bs;
    private qkg bt;
    private qkg bu;
    private qkg bv;
    private qkg bw;
    private qkg bx;
    private qkg by;
    private qkg bz;
    public final evc c = this;
    private final qkg cA;
    private final qkg cB;
    private final qkg cC;
    private final qkg cD;
    private final qkg cE;
    private final qkg cF;
    private final qkg cG;
    private final qkg cH;
    private final qkg cI;
    private final qkg cJ;
    private final qkg cK;
    private final qkg cL;
    private final qkg cM;
    private final qkg cN;
    private final qkg cO;
    private final qkg cP;
    private final qkg cQ;
    private final qkg cR;
    private final qkg cS;
    private final qkg cT;
    private final qkg cU;
    private final qkg cV;
    private final qkg cW;
    private final qkg cX;
    private final qkg cY;
    private final qkg cZ;
    private qkg ca;
    private qkg cb;
    private qkg cc;
    private qkg cd;
    private qkg ce;
    private qkg cf;
    private qkg cg;
    private qkg ch;
    private qkg ci;
    private qkg cj;
    private qkg ck;
    private qkg cl;
    private qkg cm;
    private qkg cn;
    private qkg co;
    private qkg cp;
    private qkg cq;
    private qkg cr;
    private qkg cs;
    private qkg ct;
    private qkg cu;
    private final qkg cv;
    private final qkg cw;
    private final qkg cx;
    private final qkg cy;
    private final qkg cz;
    public qkg d;
    private final qkg dA;
    private final qkg dB;
    private final qkg dC;
    private final qkg dD;
    private final qkg dE;
    private final qkg dF;
    private final qkg dG;
    private final qkg dH;
    private final qkg dI;
    private final qkg dJ;
    private final qkg dK;
    private final qkg dL;
    private final qkg dM;
    private final qkg dN;
    private final qkg dO;
    private final qkg dP;
    private final qkg da;
    private final qkg db;
    private final qkg dc;
    private final qkg dd;
    private final qkg de;
    private final qkg df;
    private final qkg dg;
    private final qkg dh;
    private final qkg di;
    private final qkg dj;
    private final qkg dk;
    private final qkg dl;
    private final qkg dm;
    private final qkg dn;

    /* JADX INFO: renamed from: do, reason: not valid java name */
    private final qkg f2do;
    private final qkg dp;
    private final qkg dq;
    private final qkg dr;
    private final qkg ds;
    private final qkg dt;
    private final qkg du;
    private final qkg dv;
    private final qkg dw;
    private final qkg dx;
    private final qkg dy;
    private final qkg dz;
    public qkg e;
    public qkg f;
    public qkg g;
    public qkg h;
    public qkg i;
    public qkg j;
    public qkg k;
    public qkg l;
    public qkg m;
    public qkg n;
    public qkg o;
    public qkg p;
    public qkg q;
    public qkg r;
    public qkg s;
    public qkg t;
    public qkg u;
    public qkg v;
    public qkg w;
    public qkg x;
    public qkg y;
    public qkg z;

    public evc(ewb ewbVar, ete eteVar, emb embVar, iid iidVar) {
        this.b = ewbVar;
        this.bo = eteVar;
        this.a = embVar;
        d(eteVar, embVar, iidVar);
        qkg qkgVarC = evv.c(ewbVar.bi);
        this.cv = qkgVarC;
        qkg qkgVarC2 = evv.c(ewbVar.bo);
        this.cw = qkgVarC2;
        cbe cbeVar = new cbe(ewbVar.i, 0);
        this.cx = cbeVar;
        qkg qkgVarB = pyr.b(new cat(ewbVar.i, ewbVar.o, this.n, ewbVar.cE, ewbVar.z, this.bV, ewbVar.az, ewbVar.y, this.r, ewbVar.cH, this.S, ewbVar.A, ewbVar.br, this.M, ewbVar.bQ, ewbVar.bt, qkgVarC, qkgVarC2, ewbVar.cJ, ewbVar.cK, ewbVar.cL, ewbVar.cN, cbeVar, ewbVar.M, ewbVar.bn));
        this.cy = qkgVarB;
        cbh cbhVar = new cbh(this.bU, qkgVarB, 0);
        this.cz = cbhVar;
        pys pysVar = pyw.a;
        List listAh = qmd.ah(0);
        List listAh2 = qmd.ah(1);
        qmd.ab(cbhVar, listAh2);
        pyw pywVarAa = qmd.aa(listAh, listAh2);
        this.cA = pywVarAa;
        cbi cbiVar = new cbi(ewbVar.N, pywVarAa);
        this.cB = cbiVar;
        qkg qkgVarB2 = pyr.b(new dpd(ewbVar.cw, this.P, cbiVar, 19));
        this.cC = qkgVarB2;
        elc elcVar = new elc(ewbVar.i, this.cu, qkgVarB2, 1, (byte[]) null);
        this.cD = elcVar;
        qkg qkgVarB3 = pyr.b(new ije(ewbVar.cw, this.P, 11));
        this.cE = qkgVarB3;
        ije ijeVar = new ije(ewbVar.i, qkgVarB3, 9, (boolean[]) null);
        this.cF = ijeVar;
        List listAh3 = qmd.ah(0);
        List listAh4 = qmd.ah(2);
        qmd.ab(elcVar, listAh4);
        qmd.ab(ijeVar, listAh4);
        pyw pywVarAa2 = qmd.aa(listAh3, listAh4);
        this.cG = pywVarAa2;
        dat datVar = new dat(ewbVar.N, pywVarAa2);
        this.cH = datVar;
        qkg qkgVarB4 = pyr.b(new cax(ewbVar.cv, this.cr, ewbVar.N, this.ct, (qkg) datVar, ewbVar.g, ewbVar.k, 9, (short[][]) null));
        this.cI = qkgVarB4;
        qkg qkgVarB5 = pyr.b(new cso(this.cq, qkgVarB4, ewbVar.k, 6, (boolean[]) null));
        this.cJ = qkgVarB5;
        hvp hvpVarB = hvp.b(ewbVar.cw, ewbVar.az);
        this.cK = hvpVarB;
        qkg qkgVarB6 = pyr.b(cly.a(this.h, this.j, hvpVarB, ewbVar.cO, ewbVar.cP, ewbVar.cQ, ewbVar.cR, ewbVar.cS, ewbVar.cT, ewbVar.i, ewbVar.t, ewbVar.o, ewbVar.l));
        this.T = qkgVarB6;
        qkg qkgVarB7 = pyr.b(edj.c(this.s, this.j, this.m, qkgVarB6, this.t, ewbVar.az));
        this.U = qkgVarB7;
        qkg qkgVarB8 = pyr.b(iwa.a(this.j, this.m, ewbVar.o, this.cd, ewbVar.k, ewbVar.i, qkgVarB7));
        this.V = qkgVarB8;
        qkg qkgVarB9 = pyr.b(new huv(ewbVar.cU, ewbVar.cW, 13));
        this.cL = qkgVarB9;
        hzj hzjVar = new hzj(ewbVar.cU);
        this.cM = hzjVar;
        qkg qkgVarB10 = pyr.b(new cbh(hzjVar, this.cs, 15));
        this.cN = qkgVarB10;
        qkg qkgVarB11 = pyr.b(new elc(ewbVar.cw, this.P, ewbVar.bH, 16, (char[][]) null));
        this.cO = qkgVarB11;
        esp espVar = new esp(this.cu, qkgVarB11, 7, (float[]) null);
        this.cP = espVar;
        qkg qkgVarB12 = pyr.b(new gth(ewbVar.cw, ewbVar.bH, this.P, 19, (float[][]) null));
        this.cQ = qkgVarB12;
        gth gthVar = new gth(ewbVar.i, this.cu, qkgVarB12, 20, (byte[][][]) null);
        this.cR = gthVar;
        qkg qkgVarB13 = pyr.b(new dpd(ewbVar.cw, this.P, ewbVar.bH, 17));
        this.cS = qkgVarB13;
        dpd dpdVar = new dpd(ewbVar.i, this.cu, qkgVarB13, 20, (boolean[][][]) null);
        this.cT = dpdVar;
        List listAh5 = qmd.ah(0);
        List listAh6 = qmd.ah(3);
        qmd.ab(espVar, listAh6);
        qmd.ab(gthVar, listAh6);
        qmd.ab(dpdVar, listAh6);
        pyw pywVarAa3 = qmd.aa(listAh5, listAh6);
        this.cU = pywVarAa3;
        cbg cbgVar = new cbg(ewbVar.N, pywVarAa3);
        this.cV = cbgVar;
        qkg qkgVarB14 = pyr.b(new bng(ewbVar.i, qkgVarC, cbgVar, 17));
        this.cW = qkgVarB14;
        boe boeVar = new boe(this.bU, this.cu, qkgVarB, qkgVarB14, 8, (char[][]) null);
        this.cX = boeVar;
        List listAh7 = qmd.ah(0);
        List listAh8 = qmd.ah(1);
        qmd.ab(boeVar, listAh8);
        pyw pywVarAa4 = qmd.aa(listAh7, listAh8);
        this.cY = pywVarAa4;
        das dasVar = new das(ewbVar.N, pywVarAa4);
        this.cZ = dasVar;
        qkg qkgVarB15 = pyr.b(new bmw(ewbVar.N, this.K, 10, (float[]) null));
        this.da = qkgVarB15;
        qkg qkgVarB16 = pyr.b(new ciu(ewbVar.t, 12));
        this.db = qkgVarB16;
        qkg qkgVarB17 = pyr.b(new czm(qkgVarB5, this.ct, ewbVar.o, this.P, qkgVarB8, qkgVarB9, qkgVarB10, this.M, ewbVar.cX, datVar, dasVar, ewbVar.i, this.r, ewbVar.F, qkgVarB15, qkgVarB16, ewbVar.aa, this.cq, ewbVar.al, ewbVar.cY));
        this.dc = qkgVarB17;
        cso csoVar = new cso(qkgVarB17, this.cq, this.d, 5, (int[]) null);
        this.dd = csoVar;
        List listAh9 = qmd.ah(7);
        List listAh10 = qmd.ah(0);
        qmd.ac(this.bZ, listAh9);
        qmd.ac(this.ca, listAh9);
        qmd.ac(this.cg, listAh9);
        qmd.ac(this.cj, listAh9);
        qmd.ac(this.ck, listAh9);
        qmd.ac(this.cm, listAh9);
        qmd.ac(csoVar, listAh9);
        pyw pywVarAa5 = qmd.aa(listAh9, listAh10);
        this.de = pywVarAa5;
        lbm lbmVar = new lbm(ewbVar.o);
        this.W = lbmVar;
        this.X = pyr.b(new clq(ewbVar.aA, this.bw, this.bA, this.bB, this.bF, this.bT, (qkg) pywVarAa5, ewbVar.bI, this.K, ewbVar.s, (qkg) lbmVar, ewbVar.k, 4, (int[]) null));
        cpk cpkVarB = cpk.b(ewbVar.az, ewbVar.cZ, ewbVar.i);
        this.Y = cpkVarB;
        this.Z = jho.b(this.m, this.s, ewbVar.ac, this.E, ewbVar.az, cpkVarB, ewbVar.cp, hvpVarB, this.p);
        this.aa = new emf(embVar);
        this.ab = new emc(embVar);
        this.ac = new emi(embVar);
        this.ad = new jbz(this.bp);
        qkg qkgVarB18 = pyr.b(new jpk(this.j, ewbVar.i, 10, (short[]) null));
        this.ae = qkgVarB18;
        this.af = new irk(ewbVar.i, 10);
        this.ag = pyr.b(new jrk(this.f, 0));
        qkg qkgVarB19 = pyr.b(new byr(6));
        this.ah = qkgVarB19;
        this.ai = pyr.b(new bng(this.q, ewbVar.dV, ewbVar.o, 11, (short[][]) null));
        this.aj = pyr.b(new cbh(ewbVar.t, qkgVarB19, 1));
        jja jjaVar = new jja(ewbVar.aT);
        this.df = jjaVar;
        jjc jjcVar = new jjc(ewbVar.F, ewbVar.ec);
        this.dg = jjcVar;
        qkg qkgVarB20 = pyr.b(new elc(ewbVar.eb, jjaVar, jjcVar, 12));
        this.dh = qkgVarB20;
        jjk jjkVar = new jjk(ewbVar.o, this.g, qkgVarB6, qkgVarB20, ewbVar.F, ewbVar.I, this.d, ewbVar.aj);
        this.di = jjkVar;
        this.ak = pyr.b(new fci((qkg) jjkVar, ewbVar.o, this.q, this.h, 2, (char[]) null));
        this.al = pyr.b(ivg.a);
        this.am = new bpk(ewbVar.f, 8);
        qkg qkgVarB21 = pyr.b(gti.a);
        this.an = qkgVarB21;
        this.ao = new gyc(this.j, ewbVar.az, qkgVarB7, ewbVar.i, 20, (float[][][]) null);
        this.ap = pyr.b(new hjt(ewbVar.i, 0));
        this.aq = pyr.b(jxc.a);
        this.ar = pyr.b(jxa.a);
        qkg qkgVarB22 = pyr.b(hxe.a);
        this.as = qkgVarB22;
        this.at = new huv(qkgVarB22, ewbVar.an, 11, (char[][]) null);
        qkg qkgVarB23 = pyr.b(hxf.a);
        this.au = qkgVarB23;
        this.av = pyr.b(new hva(qkgVarB23, 6));
        qkg qkgVarB24 = pyr.b(new jhe(ewbVar.o, ewbVar.i, this.j, 0));
        this.aw = qkgVarB24;
        qkg qkgVarB25 = pyr.b(jbd.a);
        this.dj = qkgVarB25;
        qkg qkgVarB26 = pyr.b(new itu(this.m, ewbVar.i, ewbVar.o, qkgVarB25, 4));
        this.ax = qkgVarB26;
        this.ay = pyr.b(new itu(this.m, qkgVarB26, ewbVar.az, ewbVar.i, 5, (int[]) null));
        ikn iknVar = new ikn(this.j, ewbVar.i);
        this.dk = iknVar;
        this.az = pyr.b(new hva(iknVar, 13));
        ilh ilhVar = new ilh(ewbVar.dA, ewbVar.dQ, ewbVar.dK, ewbVar.dI, ewbVar.dH, ewbVar.az);
        this.dl = ilhVar;
        qkg qkgVarB27 = pyr.b(new hcv(this.j, this.f, qkgVarB7, (qkg) ilhVar, ewbVar.t, ewbVar.o, this.h, ewbVar.i, 10, (int[][]) null));
        this.aA = qkgVarB27;
        qkg qkgVarB28 = pyr.b(dbb.a);
        this.dm = qkgVarB28;
        qkg qkgVarB29 = pyr.b(new cbh(ewbVar.eU, ewbVar.i, 18, (char[][]) null));
        this.dn = qkgVarB29;
        qkg qkgVarB30 = pyr.b(new bqq(qkgVarC, qkgVarB29, this.M, this.f, ewbVar.bH, ewbVar.t, 14, (char[][][]) null));
        this.aB = qkgVarB30;
        qkg qkgVarB31 = pyr.b(new ciu(ewbVar.i, 15));
        this.f2do = qkgVarB31;
        qkg qkgVarB32 = pyr.b(new bqq(qkgVarC2, qkgVarB31, this.M, this.f, ewbVar.bH, ewbVar.t, 15, (short[][][]) null));
        this.aC = qkgVarB32;
        qkg qkgVarB33 = pyr.b(new bsr(qkgVarC2, qkgVarB28, this.M, this.f, ewbVar.bH, ewbVar.i, qkgVarB30, ewbVar.eU, qkgVarB32, ewbVar.t, 4, (int[]) null));
        this.aD = qkgVarB33;
        qkg qkgVarB34 = pyr.b(new bqr(ewbVar.g, 3));
        this.dp = qkgVarB34;
        qkg qkgVarB35 = pyr.b(btr.a);
        this.aE = qkgVarB35;
        this.aF = pyr.b(new btq(qkgVarB34, ewbVar.aU, ewbVar.ab, ewbVar.ck, ewbVar.aR, ewbVar.eW, qkgVarB35, this.q, 0));
        this.aG = pyr.b(cpr.a);
        this.aH = pyr.b(fxm.a);
        this.aI = new cwo(this.p);
        this.aJ = pyr.b(cuy.a);
        qkg qkgVarA = pyx.a(hjt.c(ewbVar.h));
        this.dq = qkgVarA;
        qkg qkgVarB36 = pyr.b(new edj(ewbVar.cw, this.P, ewbVar.bH, ewbVar.eg, qkgVarA, cbiVar, 6, (float[]) null));
        this.aK = qkgVarB36;
        this.aL = pyr.b(new esp(this.M, this.R, 18));
        this.aM = pyr.b(new bqr(this.cc, 14));
        this.aN = pyr.b(new elu(this.j, 4));
        qkg qkgVarB37 = pyr.b(new elc(ewbVar.et, this.f, ewbVar.i, 20, (float[][]) null));
        this.dr = qkgVarB37;
        qkg qkgVarC3 = evv.c(qkgVarB37);
        this.ds = qkgVarC3;
        this.aO = new cjc(qkgVarC3, ewbVar.an, 15);
        qkg qkgVarB38 = pyr.b(new cso(ewbVar.eU, ewbVar.t, ewbVar.i, 10, (char[][]) null));
        this.dt = qkgVarB38;
        qkg qkgVarB39 = pyr.b(new cax(qkgVarB38, this.j, qkgVarB7, qkgVarC, ewbVar.t, ewbVar.bH, ewbVar.i, 11, (boolean[][]) null));
        this.aP = qkgVarB39;
        this.aQ = pyr.b(new ije(ewbVar.g, ewbVar.aE, 20, (float[][]) null));
        this.aR = pyr.b(new bqr(this.cc, 16));
        this.aS = pyr.b(new bqr(this.cc, 13));
        qkg qkgVarB40 = pyr.b(new hva(qkgVarB22, 7));
        this.aT = qkgVarB40;
        this.aU = new boe(qkgVarB17, qkgVarB40, ewbVar.o, this.cq, 20, (char[]) null, (byte[]) null);
        iug iugVarB = iug.b(ewbVar.dh);
        this.du = iugVarB;
        qkg qkgVarB41 = pyr.b(new iaa(ewbVar.o, ewbVar.t, iugVarB, ewbVar.dW, ewbVar.i, 0));
        this.dv = qkgVarB41;
        qkg qkgVarB42 = pyr.b(new hcv(this.j, ewbVar.N, ewbVar.t, qkgVarB41, ewbVar.dW, qkgVarB8, this.P, qkgVarB18, 7, (byte[][]) null));
        this.aV = qkgVarB42;
        eej eejVar = new eej(qkgVarB21, qkgVarB25, this.w, this.j, 2, (char[]) null);
        this.dw = eejVar;
        qkg qkgVarB43 = pyr.b(new hcu(ewbVar.cU, qkgVarB41, qkgVarB42, this.L, ewbVar.cE, ewbVar.fm, ewbVar.de, this.f, eejVar, ewbVar.k, 6, (float[]) null));
        this.aW = qkgVarB43;
        this.aX = new hxg(qkgVarB43, ewbVar.o, this.h);
        this.aY = new bmw(this.ci, this.e, 3, (char[]) null);
        qkg qkgVarB44 = pyr.b(new bpw(5));
        this.dx = qkgVarB44;
        bte bteVar = new bte(ewbVar.g, qkgVarB44);
        this.dy = bteVar;
        qkg qkgVarB45 = pyr.b(new bmw(bteVar, ewbVar.i, 9));
        this.dz = qkgVarB45;
        dkv dkvVar = new dkv(ewbVar.g);
        this.dA = dkvVar;
        dla dlaVar = new dla(this.j, this.f, qkgVarB44, qkgVarB8, ewbVar.t, ewbVar.s, ewbVar.i);
        this.dB = dlaVar;
        qkg qkgVarB46 = pyr.b(new bno((qkg) dkvVar, (qkg) dlaVar, this.f, ewbVar.s, ewbVar.N, 10, (int[][]) null));
        this.dC = qkgVarB46;
        dlb dlbVar = new dlb(qkgVarB46, ewbVar.i, this.q);
        this.dD = dlbVar;
        this.aZ = new dlf(qkgVarB45, dlbVar, this.n, ewbVar.o, 0);
        this.ba = new bng(this.bU, qkgVarB40, qkgVarB, 12);
        this.bb = new bng(this.cu, qkgVarB40, qkgVarB14, 14, (boolean[][]) null);
        fge fgeVar = new fge(ewbVar.i, qkgVarB8);
        this.dE = fgeVar;
        fgf fgfVar = new fgf(ewbVar.g);
        this.dF = fgfVar;
        ffb ffbVar = new ffb(ewbVar.fV);
        this.dG = ffbVar;
        ffd ffdVar = new ffd(ffbVar, ewbVar.t);
        this.dH = ffdVar;
        qkg qkgVarB47 = pyr.b(new fnk(ewbVar.g, this.q, ewbVar.cX, ewbVar.i, this.j, this.co, this.cn, dasVar, datVar, qkgVarB8, fgeVar, qkgVarB7, ewbVar.t, this.P, ewbVar.N, qkgVarB9, ewbVar.o, fgfVar, ffdVar, 1, (byte[]) null));
        this.dI = qkgVarB47;
        ffg ffgVar = new ffg(ewbVar.i, this.co, this.cn, 0);
        this.dJ = ffgVar;
        ffa ffaVar = new ffa(ewbVar.N, ewbVar.fW, ffgVar);
        this.dK = ffaVar;
        this.bc = new cax(ewbVar.i, qkgVarB40, qkgVarB47, ewbVar.al, ffaVar, this.q, ffgVar, 19, (byte[]) null, (byte[]) null);
        qkg qkgVarB48 = pyr.b(new cax(ewbVar.cw, ewbVar.g, ewbVar.az, this.P, ewbVar.i, ewbVar.bH, cbiVar, 20, (char[]) null, (byte[]) null));
        this.dL = qkgVarB48;
        qkg qkgVarB49 = pyr.b(new fci(ewbVar.cw, this.P, ewbVar.az, qkgVarB24, 3, (short[]) null));
        this.dM = qkgVarB49;
        this.bd = new bsr(qkgVarB40, qkgVarB36, qkgVarB48, qkgVarB11, qkgVarB49, ewbVar.i, this.cu, ewbVar.fm, this.f, this.q, 7, (byte[][]) null);
        qkg qkgVarB50 = pyr.b(new hah(ewbVar.cw, this.P, ewbVar.bP, ewbVar.bH, cbiVar, 6, (float[]) null));
        this.dN = qkgVarB50;
        this.be = new hah(ewbVar.i, qkgVarB40, this.cu, qkgVarB50, qkgVarB12, 4, (int[]) null);
        qkg qkgVarB51 = pyr.b(new edj(ewbVar.i, ewbVar.bf, this.f, this.q, this.n, ewbVar.o, 4, (int[]) null));
        this.dO = qkgVarB51;
        pyr.b(new esc(ewbVar.cw, this.P, ewbVar.eh, qkgVarB51, ewbVar.bQ, ewbVar.bH, this.q, ewbVar.k, cbiVar, qkgVarA, ewbVar.i, 0));
        this.bf = new eeh(ewbVar.i, qkgVarB40, 17);
        this.bg = pyr.b(new huv(ewbVar.o, this.r, 16));
        this.bh = new boe(this.q, ewbVar.em, this.p, ewbVar.fX, 2, (char[]) null);
        this.bi = new cax(ewbVar.i, ewbVar.dZ, qkgVarB40, qkgVarB30, qkgVarB32, qkgVarB39, qkgVarB33, 10, (int[][]) null);
        this.bj = new elt(ewbVar.i, qkgVarB40, this.cu, qkgVarB2, qkgVarB13, 1, (byte[]) null);
        this.bk = new ije(qkgVarB40, qkgVarB27, 5, (short[]) null);
        this.bl = new hvz(ewbVar.i, qkgVarB40, qkgVarB3, 13, (int[][]) null);
        qkg qkgVarB52 = pyr.b(new ije(this.m, ewbVar.o, 19, (boolean[][]) null));
        this.dP = qkgVarB52;
        this.bm = new jhe(this.h, ewbVar.o, qkgVarB52, 1, (byte[]) null);
        this.bn = pyr.b(new bqq(ewbVar.g, ewbVar.i, this.h, this.L, this.cd, ewbVar.k, 3, (short[]) null));
    }

    private final ojz c() {
        return jbz.b((AtomicReference) this.bp.get());
    }

    private final void d(ete eteVar, emb embVar, iid iidVar) {
        this.bp = pyr.b(jby.a);
        emj emjVarB = emj.b(embVar);
        this.d = emjVarB;
        jrj jrjVar = new jrj(emjVarB);
        this.e = jrjVar;
        this.f = pyr.b(new jrk(jrjVar, 1));
        this.g = new emg(embVar);
        this.bq = new imk(this.b.o, this.g);
        this.h = etj.a(eteVar);
        this.i = pyr.b(new hvz(this.bq, this.b.o, this.h, 11, (short[][]) null));
        this.j = emd.b(embVar);
        emk emkVarA = emk.a(embVar);
        this.k = emkVarA;
        this.l = pyr.b(bmw.b(emkVarA, this.b.o));
        eme emeVarB = eme.b(embVar);
        this.m = emeVarB;
        qkg qkgVar = this.j;
        qkg qkgVar2 = this.l;
        ewb ewbVar = this.b;
        this.br = pyr.b(cax.c(qkgVar, qkgVar2, emeVarB, ewbVar.t, ewbVar.r, ewbVar.aw, ewbVar.i));
        this.n = etf.a(eteVar);
        this.bs = pyr.b(cso.a(this.b.o, this.n, this.m));
        ewb ewbVar2 = this.b;
        this.o = pyr.b(bqq.b(ewbVar2.o, ewbVar2.bF, this.br, ewbVar2.aw, ewbVar2.r, this.bs));
        qkg qkgVar3 = this.j;
        qkg qkgVar4 = this.l;
        qkg qkgVar5 = this.m;
        ewb ewbVar3 = this.b;
        qkg qkgVarB = pyr.b(cax.a(qkgVar3, qkgVar4, qkgVar5, ewbVar3.t, ewbVar3.r, ewbVar3.aw, ewbVar3.i));
        this.bt = qkgVarB;
        ewb ewbVar4 = this.b;
        this.bu = pyr.b(cax.b(qkgVarB, ewbVar4.o, ewbVar4.bF, ewbVar4.aw, ewbVar4.t, ewbVar4.r, this.bs));
        ewb ewbVar5 = this.b;
        this.p = pyr.b(btq.a(ewbVar5.ac, ewbVar5.o, this.o, this.bu, ewbVar5.bF, ewbVar5.aw, ewbVar5.aS, this.d));
        this.q = etg.a(eteVar);
        qkg qkgVar6 = this.k;
        ewb ewbVar6 = this.b;
        this.bv = new dlj(qkgVar6, ewbVar6.t, ewbVar6.I, this.f, ewbVar6.aw);
        ewb ewbVar7 = this.b;
        this.bw = pyr.b(new bno(ewbVar7.aS, this.q, this.n, this.bv, ewbVar7.o, 11, (boolean[][]) null));
        this.bx = pyr.b(new huv(this.j, this.b.i, 9));
        ewb ewbVar8 = this.b;
        qkg qkgVarB2 = pyr.b(new iaa(ewbVar8.aF, this.bx, ewbVar8.aI, ewbVar8.aH, ewbVar8.o, 1, (byte[]) null));
        this.by = qkgVarB2;
        qkg qkgVarC = evv.c(qkgVarB2);
        this.bz = qkgVarC;
        this.bA = new hva(qkgVarC, 4);
        this.r = pyr.b(new iie(iidVar));
        ewb ewbVar9 = this.b;
        this.bB = pyr.b(new bqq(ewbVar9.ay, this.bu, this.r, ewbVar9.aw, ewbVar9.aS, ewbVar9.N, 0));
        bqr bqrVar = new bqr(this.m, 0);
        this.bC = bqrVar;
        this.bD = pyr.b(bqrVar);
        this.s = eti.a(eteVar);
        this.t = pyr.b(hgg.b(this.m, this.b.bJ));
        qkg qkgVar7 = this.m;
        qkg qkgVar8 = this.l;
        qkg qkgVar9 = this.h;
        ewb ewbVar10 = this.b;
        bsr bsrVar = new bsr(qkgVar7, qkgVar8, qkgVar9, ewbVar10.bG, this.bD, this.s, ewbVar10.o, ewbVar10.bI, this.t, ewbVar10.i, 1, (byte[]) null);
        this.bE = bsrVar;
        qkg qkgVarB3 = pyr.b(bsrVar);
        this.u = qkgVarB3;
        this.bF = pyr.b(new bmw(qkgVarB3, this.r, 5));
        ewb ewbVar11 = this.b;
        this.v = pyr.b(new hhg(ewbVar11.o, ewbVar11.i, this.f, 4, (int[]) null));
        emh emhVar = new emh(embVar);
        this.w = emhVar;
        this.x = pyr.b(new elu(emhVar, 3));
        qkg qkgVarB4 = pyr.b(new eeh(this.j, this.b.i, 19));
        this.bG = qkgVarB4;
        qkg qkgVarC2 = evv.c(qkgVarB4);
        this.bH = qkgVarC2;
        this.y = pyr.b(new esp(qkgVarC2, this.b.i, 1));
        ewb ewbVar12 = this.b;
        clq clqVar = new clq(ewbVar12.o, ewbVar12.G, this.v, ewbVar12.bK, ewbVar12.bL, ewbVar12.ac, this.x, this.r, ewbVar12.bM, this.p, ewbVar12.aU, this.y, 7, (byte[][]) null);
        this.bI = clqVar;
        this.z = pyr.b(clqVar);
        ewb ewbVar13 = this.b;
        this.A = new fbg(ewbVar13.bN, ewbVar13.k);
        pys pysVar = pyw.a;
        List listAh = qmd.ah(0);
        List listAh2 = qmd.ah(1);
        qmd.ab(this.b.cf, listAh2);
        this.B = qmd.aa(listAh, listAh2);
        List listAh3 = qmd.ah(0);
        List listAh4 = qmd.ah(5);
        qmd.ab(this.b.bS, listAh4);
        qmd.ab(this.b.bY, listAh4);
        qmd.ab(this.b.cc, listAh4);
        qmd.ab(this.b.ce, listAh4);
        qmd.ab(this.B, listAh4);
        this.bJ = qmd.aa(listAh3, listAh4);
        ewb ewbVar14 = this.b;
        iaa iaaVar = new iaa(ewbVar14.i, ewbVar14.k, ewbVar14.cg, this.r, this.p, 10, (int[][]) null);
        this.bK = iaaVar;
        qkg qkgVarB5 = pyr.b(iaaVar);
        this.C = qkgVarB5;
        ewk ewkVarA = ewk.a(this.bJ, qkgVarB5, this.b.i);
        this.bL = ewkVarA;
        this.D = pyr.b(new elc(this.z, this.A, ewkVarA, 4));
        ewb ewbVar15 = this.b;
        this.E = hvh.b(ewbVar15.v, ewbVar15.ac, ewbVar15.i);
        qkg qkgVar10 = this.w;
        ewb ewbVar16 = this.b;
        this.bM = new jmu(qkgVar10, ewbVar16.i, ewbVar16.ch);
        qkg qkgVar11 = this.w;
        ewb ewbVar17 = this.b;
        this.bN = new jmw(qkgVar11, ewbVar17.i, ewbVar17.ab, ewbVar17.ch);
        this.F = pyr.b(new jhe(this.b.i, this.bM, this.bN, 3, (short[]) null));
        ewb ewbVar18 = this.b;
        fwa fwaVar = new fwa(ewbVar18.ac, this.E, this.F, ewbVar18.k);
        this.bO = fwaVar;
        this.G = new fwj(fwaVar, this.b.s);
        ewb ewbVar19 = this.b;
        this.bP = pyr.b(new fci(ewbVar19.ac, this.d, ewbVar19.ad, ewbVar19.i, 12, (int[][]) null));
        qkg qkgVarB6 = pyr.b(jnh.a);
        this.H = qkgVarB6;
        qkg qkgVarB7 = pyr.b(new fsy(this.G, this.bP, qkgVarB6, 13, (byte[][][]) null));
        this.bQ = qkgVarB7;
        this.bR = pyr.b(new esp(this.D, qkgVarB7, 4, (short[]) null));
        qkg qkgVarB8 = pyr.b(new elc(this.z, this.A, this.bL, 9));
        this.I = qkgVarB8;
        esp espVar = new esp(qkgVarB8, this.bQ, 3, (char[]) null);
        this.bS = espVar;
        qkg qkgVar12 = this.e;
        qkg qkgVar13 = this.bR;
        ewb ewbVar20 = this.b;
        this.bT = pyr.b(new elt(qkgVar12, qkgVar13, espVar, ewbVar20.ci, ewbVar20.k, 5, (boolean[]) null));
        this.bU = new bpk(this.b.i, 3);
        this.bV = new cbj(this.j);
        this.bW = new cbf(this.b.i);
        qkg qkgVar14 = this.j;
        ewb ewbVar21 = this.b;
        this.bX = new cdv(qkgVar14, ewbVar21.x, ewbVar21.i, this.bV, ewbVar21.cj, ewbVar21.o, this.n, this.bW);
        qkg qkgVar15 = this.j;
        ewb ewbVar22 = this.b;
        cdx cdxVar = new cdx(qkgVar15, ewbVar22.x, ewbVar22.o, this.n, this.bW, ewbVar22.z);
        this.bY = cdxVar;
        this.bZ = pyr.b(new bng(this.bU, this.bX, (qkg) cdxVar, 13, (int[][]) null));
        this.ca = new dlf(this.f, this.b.bR, this.p, this.q, 5, (boolean[]) null);
        this.J = new eth(eteVar);
        this.cb = pyr.b(new hva(this.r, 10));
        ewb ewbVar23 = this.b;
        qkg qkgVarB9 = pyr.b(bng.b(ewbVar23.F, ewbVar23.w, this.q));
        this.cc = qkgVarB9;
        qkg qkgVarB10 = pyr.b(bmw.d(qkgVarB9, this.b.G));
        this.K = qkgVarB10;
        this.L = pyr.b(new bqr(qkgVarB10, 15));
        this.cd = pyr.b(bmw.c(this.b.bI, this.K));
        qkg qkgVar16 = this.m;
        ewb ewbVar24 = this.b;
        this.ce = new gvf(qkgVar16, ewbVar24.bm, this.w, ewbVar24.s, this.q, this.cd, ewbVar24.k);
        this.M = pyr.b(new gth(this.h, this.b.o, this.ce, 3));
        ewb ewbVar25 = this.b;
        this.cf = new htw(ewbVar25.h, ewbVar25.az, ewbVar25.cm, ewbVar25.cn);
        ewb ewbVar26 = this.b;
        this.N = pyr.b(new cly(ewbVar26.g, this.J, ewbVar26.t, this.r, ewbVar26.ck, this.cb, this.L, ewbVar26.k, this.f, ewbVar26.cl, this.M, this.cf, ewbVar26.co, 1, (byte[]) null));
        this.cg = new bng(this.b.o, this.h, this.N, 2, (char[]) null);
        ewb ewbVar27 = this.b;
        iaa iaaVar2 = new iaa(ewbVar27.cq, ewbVar27.k, ewbVar27.o, this.n, ewbVar27.az, 2, (char[]) null);
        this.ch = iaaVar2;
        qkg qkgVarB11 = pyr.b(iaaVar2);
        this.O = qkgVarB11;
        qkg qkgVarB12 = pyr.b(new huv(qkgVarB11, this.b.k, 14));
        this.ci = qkgVarB12;
        this.cj = new bmw(qkgVarB12, this.e, 2, (byte[]) null);
        qkg qkgVar17 = this.f;
        ewb ewbVar28 = this.b;
        this.ck = new bqq(qkgVar17, ewbVar28.cr, ewbVar28.bU, ewbVar28.bX, ewbVar28.cs, ewbVar28.cu, 17, (boolean[][][]) null);
        this.cl = pyr.b(new hhg(this.j, this.l, this.b.s, 3, (short[]) null));
        this.cm = pyr.b(new gyc(this.b.o, this.m, this.h, this.cl, 16, (char[][][]) null));
        this.cn = new bpk(this.b.i, 5);
        this.co = new bpk(this.b.i, 4);
        this.cp = new cyi(this.b.g);
        this.cq = pyr.b(new boe(this.b.i, this.cn, this.co, this.cp, 19, (byte[]) null, (byte[]) null));
        this.cr = new czw(this.b.F);
        this.cs = pyr.b(cys.a);
        this.ct = pyr.b(new cbh(this.b.k, this.cs, 16, (byte[][]) null));
        this.cu = new bpk(this.b.i, 2);
        this.P = pyr.b(fvu.a);
        this.Q = new jrs(this.M);
        qkg qkgVarB13 = pyr.b(new irk(this.m, 9));
        this.R = qkgVarB13;
        qkg qkgVar18 = this.Q;
        ewb ewbVar29 = this.b;
        this.S = pyr.b(new cax(qkgVar18, qkgVarB13, ewbVar29.ac, this.p, this.q, ewbVar29.i, ewbVar29.ad, 0));
    }

    @Override // defpackage.jca
    public final void a(GcaLayout gcaLayout) {
        gcaLayout.d = c();
    }

    @Override // defpackage.jot
    public final void b(MainActivityLayout mainActivityLayout) {
        ((GcaLayout) mainActivityLayout).d = c();
        mainActivityLayout.r = (AtomicReference) this.bp.get();
        mainActivityLayout.s = (lda) this.f.get();
        mainActivityLayout.t = (img) this.i.get();
        mainActivityLayout.u = (ddf) this.b.i.get();
        mainActivityLayout.x = etf.c(this.bo);
        mainActivityLayout.v = pyr.a(this.p);
        mainActivityLayout.w = (lzi) this.b.e.get();
    }
}
