package defpackage;

import java.util.List;
import java.util.concurrent.Executor;

/* JADX INFO: loaded from: classes.dex */
public final class evo implements cot {
    private final qkg A;
    private final qkg B;
    private final qkg C;
    private final qkg D;
    private final qkg E;
    private final qkg F;
    private final qkg G;
    private final qkg H;
    private final qkg I;
    private final qkg J;
    private final qkg K;
    private final qkg L;
    private final qkg M;
    private final qkg N;
    private final qkg O;
    private final qkg P;
    private final qkg Q;
    private final qkg R;
    private final qkg S;
    private final qkg T;
    private final qkg U;
    private final qkg V;
    private final qkg W;
    private final qkg X;
    private final qkg Y;
    private final qkg Z;
    private final cou a;
    private final qkg aa;
    private final qkg ab;
    private final qkg ac;
    private final qkg ad;
    private final qkg ae;
    private final qkg af;
    private final qkg ag;
    private final ewb b;
    private final qkg c;
    private final qkg d;
    private final qkg e;
    private final qkg f;
    private final qkg g;
    private final qkg h;
    private final qkg i;
    private final qkg j;
    private final qkg k;
    private final qkg l;
    private final qkg m;
    private final qkg n;
    private final qkg o;
    private final qkg p;
    private final qkg q;
    private final qkg r;
    private final qkg s;
    private final qkg t;
    private final qkg u;
    private final qkg v;
    private final qkg w;
    private final qkg x;
    private final qkg y;
    private final qkg z;

    public evo(ewb ewbVar, com comVar, cou couVar) {
        this.b = ewbVar;
        this.a = couVar;
        pyr.b(coz.a);
        pys pysVar = pyw.a;
        List listAh = qmd.ah(1);
        List listAh2 = qmd.ah(0);
        qmd.ac(ewbVar.aW, listAh);
        pyw pywVarAa = qmd.aa(listAh, listAh2);
        this.c = pywVarAa;
        qkg qkgVarB = pyr.b(dhv.f(ewbVar.aV, pywVarAa));
        this.d = qkgVarB;
        qkg qkgVarB2 = pyr.b(gnj.a);
        this.e = qkgVarB2;
        this.f = pyr.b(gcc.i(ewbVar.N, qkgVarB2));
        cop copVar = new cop(comVar);
        this.g = copVar;
        con conVar = new con(comVar);
        this.h = conVar;
        qkg qkgVarB3 = pyr.b(conVar);
        this.i = qkgVarB3;
        qkg qkgVarB4 = pyr.b(dhv.e(copVar, qkgVarB3));
        this.j = qkgVarB4;
        dhv dhvVarH = dhv.h(ewbVar.i, qkgVarB);
        this.k = dhvVarH;
        qkg qkgVarB5 = pyr.b(gnc.a);
        this.l = qkgVarB5;
        gih gihVarS = gih.s(qkgVarB5);
        this.m = gihVarS;
        cow cowVar = new cow(couVar, ewbVar.ac, ewbVar.i);
        this.n = cowVar;
        qkg qkgVarB6 = pyr.b(dvd.h(cowVar, ewbVar.i));
        this.o = qkgVarB6;
        csn csnVar = new csn(copVar);
        this.p = csnVar;
        coo cooVar = new coo(comVar);
        this.q = cooVar;
        cso csoVar = new cso(copVar, csnVar, cooVar, 0);
        this.r = csoVar;
        qkg qkgVarB7 = pyr.b(dvd.g(qkgVarB6, csoVar));
        this.s = qkgVarB7;
        dsd dsdVarD = dsd.d(qkgVarB7);
        this.t = dsdVarD;
        List listAh3 = qmd.ah(1);
        List listAh4 = qmd.ah(2);
        qmd.ab(dhvVarH, listAh4);
        qmd.ac(gihVarS, listAh3);
        qmd.ab(dsdVarD, listAh4);
        pyw pywVarAa2 = qmd.aa(listAh3, listAh4);
        this.u = pywVarAa2;
        qkg qkgVarB8 = pyr.b(gcc.j(pywVarAa2, ewbVar.aX));
        this.v = qkgVarB8;
        qkg qkgVarB9 = pyr.b(dhx.a(qkgVarB8));
        this.w = qkgVarB9;
        qkg qkgVarB10 = pyr.b(dhv.d(copVar, qkgVarB4));
        this.x = qkgVarB10;
        qkg qkgVarB11 = pyr.b(dpd.c(copVar, qkgVarB10, qkgVarB8));
        this.y = qkgVarB11;
        List listAh5 = qmd.ah(11);
        List listAh6 = qmd.ah(0);
        qmd.ac(ewbVar.aY, listAh5);
        qmd.ac(ewbVar.aZ, listAh5);
        qmd.ac(ewbVar.ba, listAh5);
        qmd.ac(ewbVar.bb, listAh5);
        qmd.ac(ewbVar.bc, listAh5);
        qmd.ac(ewbVar.bd, listAh5);
        qmd.ac(ewbVar.be, listAh5);
        qmd.ac(ewbVar.bh, listAh5);
        qmd.ac(ewbVar.bl, listAh5);
        qmd.ac(ewbVar.bp, listAh5);
        qmd.ac(ewbVar.bs, listAh5);
        pyw pywVarAa3 = qmd.aa(listAh5, listAh6);
        this.z = pywVarAa3;
        qkg qkgVarB12 = pyr.b(dlf.b(qkgVarB9, qkgVarB11, qkgVarB4, pywVarAa3));
        this.A = qkgVarB12;
        brh brhVarB = brh.b(ewbVar.bm, ewbVar.bn, cowVar, ewbVar.i);
        this.B = brhVarB;
        cax caxVarD = cax.d(ewbVar.i, qkgVarB4, qkgVarB12, cowVar, brhVarB, qkgVarB5, ewbVar.k);
        this.C = caxVarD;
        qkg qkgVarB13 = pyr.b(gni.a);
        this.D = qkgVarB13;
        qkg qkgVarB14 = pyr.b(gcc.h(ewbVar.N, qkgVarB13));
        this.E = qkgVarB14;
        qkg qkgVarB15 = pyr.b(new bqq(ewbVar.g, (qkg) cowVar, ewbVar.i, qkgVarB14, ewbVar.k, ewbVar.bt, 10, (int[][]) null));
        this.F = qkgVarB15;
        this.G = pyr.b(dvd.d(ewbVar.bg, qkgVarB8));
        qkg qkgVarB16 = pyr.b(dvd.f(ewbVar.bg, ewbVar.i));
        this.H = qkgVarB16;
        qkg qkgVarB17 = pyr.b(dpd.f(ewbVar.bu, csnVar, cowVar));
        this.I = qkgVarB17;
        qkg qkgVarB18 = pyr.b(jhe.a(ewbVar.ab, cowVar, ewbVar.i));
        this.J = qkgVarB18;
        qkg qkgVarB19 = pyr.b(bqq.d(ewbVar.i, cowVar, qkgVarB18, ewbVar.bu, qkgVarB7, csoVar));
        this.K = qkgVarB19;
        qkg qkgVarB20 = pyr.b(new cso(qkgVarB16, qkgVarB17, qkgVarB19, 1));
        this.L = qkgVarB20;
        fub fubVarB = fub.b(qkgVarB20);
        this.M = fubVarB;
        qkg qkgVarB21 = pyr.b(hjt.a(fubVarB));
        this.N = qkgVarB21;
        qkg qkgVarB22 = pyr.b(hlf.a);
        this.O = qkgVarB22;
        qkg qkgVarB23 = pyr.b(hkl.a);
        this.P = qkgVarB23;
        hkf hkfVarB = hkf.b(ewbVar.bv, ewbVar.bw, ewbVar.bx, ewbVar.by);
        this.Q = hkfVarB;
        qkg qkgVarC = evv.c(ewbVar.bo);
        this.R = qkgVarC;
        qkg qkgVarB24 = pyr.b(hkj.a(qkgVarB15, qkgVarB21, qkgVarB22, qkgVarB23, hkfVarB, ewbVar.bk, qkgVarC, csl.a, ewbVar.bv, ewbVar.bz, ewbVar.bA, qkgVarB8));
        this.S = qkgVarB24;
        qkg qkgVarB25 = pyr.b(new cax((qkg) copVar, (qkg) brhVarB, (qkg) conVar, qkgVarB24, ewbVar.bB, qkgVarB18, qkgVarB8, 4, (int[]) null));
        this.T = qkgVarB25;
        boe boeVar = new boe((qkg) cooVar, qkgVarB25, ewbVar.bD, qkgVarB8, 15, (short[][][]) null);
        this.U = boeVar;
        ciu ciuVar = new ciu(cooVar, 8);
        this.V = ciuVar;
        qkg qkgVarB26 = pyr.b(esp.f(qkgVarB20, ciuVar));
        this.W = qkgVarB26;
        cbh cbhVar = new cbh(qkgVarB8, qkgVarB26, 10, (int[]) null);
        this.X = cbhVar;
        cbh cbhVar2 = new cbh(cooVar, ewbVar.bC, 11, (boolean[]) null);
        this.Y = cbhVar2;
        List listAh7 = qmd.ah(3);
        List listAh8 = qmd.ah(1);
        qmd.ab(caxVarD, listAh8);
        qmd.ac(boeVar, listAh7);
        qmd.ac(cbhVar, listAh7);
        qmd.ac(cbhVar2, listAh7);
        this.Z = qmd.aa(listAh7, listAh8);
        dsd dsdVarC = dsd.c(qkgVarB7);
        this.aa = dsdVarC;
        List listAh9 = qmd.ah(1);
        List listAh10 = qmd.ah(0);
        qmd.ac(dsdVarC, listAh9);
        pyw pywVarAa4 = qmd.aa(listAh9, listAh10);
        this.ab = pywVarAa4;
        qkg qkgVarB27 = pyr.b(dlf.g(qkgVarB6, ewbVar.bE, pywVarAa4, pyw.a));
        this.ac = qkgVarB27;
        dvd dvdVarE = dvd.e(qkgVarB6, qkgVarB27);
        this.ad = dvdVarE;
        List listAh11 = qmd.ah(0);
        List listAh12 = qmd.ah(1);
        qmd.ab(dvdVarE, listAh12);
        pyw pywVarAa5 = qmd.aa(listAh11, listAh12);
        this.ae = pywVarAa5;
        coq coqVar = new coq(comVar);
        this.af = coqVar;
        this.ag = pyr.b(gqr.l(pywVarAa5, coqVar));
    }

    @Override // defpackage.cot
    public final cos a() {
        nvb nvbVar = this.a.b;
        qmd.ae(nvbVar);
        ohh.U(4, "expectedSize");
        opc opcVar = new opc(null);
        opcVar.i(dhv.a((ddf) this.b.i.get(), this.d));
        opcVar.d(fci.a((Executor) this.b.N.get(), (Executor) this.f.get(), this.Z, pyw.a));
        opcVar.d(fsy.b((lap) this.v.get(), (pht) this.D.get(), (bxj) this.b.G.get()));
        opcVar.d((bvv) this.ag.get());
        return new cos(nvbVar, new gmy(opcVar.f(), (pih) this.e.get(), (Executor) this.E.get(), (ljf) this.b.k.get()), (lap) this.v.get(), (pih) this.D.get(), (lbu) this.b.aX.get(), null, null);
    }
}
