package defpackage;

/* JADX INFO: loaded from: classes2.dex */
public enum hib {
    CREATE_EARLY_FILMSTRIP_PREVIEW,
    COMPRESS_TO_JPEG_AND_WRITE_TO_DISK,
    CONVERT_TO_RGB_PREVIEW,
    BLOCK_UNTIL_ALL_TASKS_RELEASE,
    CLOSE_ON_ALL_TASKS_RELEASE
}
