package defpackage;

/* JADX INFO: loaded from: classes2.dex */
public final class htu {
    public static final huk A;
    public static final huk B;
    public static final huk C;
    public static final huk D;
    public static final huk E;
    public static final huk F;
    public static final huk G;
    public static final huk H;
    public static final hun I;
    public static final hul J;
    public static final huk K;
    public static final huk L;
    public static final hun M;
    public static final hun N;
    public static final hum O;
    public static final hum P;
    public static final hul Q;
    public static final hul R;
    public static final hum S;
    public static final hum T;
    public static final hul U;
    public static final hul V;
    public static final hul W;
    public static final hul X;
    public static final hul Y;
    public static final hul Z;
    public static final hun aa;
    public static final huk ab;
    public static final hum ac;
    public static final hul w;
    public static final hul x;
    public static final huk y;
    public static final huk z;
    public static final huk a = new huk("pref_camera_recordlocation_key", htt.b);
    public static final huk b = new huk("pref_dirty_lens_detector_key", (Boolean) true);
    public static final hul c = new hul("pref_camera_grid_lines_mode", Integer.valueOf(jbp.OFF.e));
    public static final hul d = new hul(htt.a);
    public static final hun e = new hun("pref_double_tap_key", "zoom");
    public static final hun f = new hun("pref_volume_key_action", "shutter");
    public static final huk g = new huk("pref_camera_sounds_key", (Boolean) true);
    public static final huk h = new huk("pref_camera_single_shot_sound_key", (Boolean) false);
    public static final hun i = new hun("pref_camera_back_flashmode_key", htt.c);
    public static final hun j = new hun("pref_camera_front_flashmode_key", htt.d);
    public static final huk k = new huk("pref_camera_selfie_flashmode_key", (Boolean) false);
    public static final hun l = new hun("pref_camera_video_back_flashmode_key", "off");
    public static final hun m = new hun("pref_camera_video_front_flashmode_key", "off");
    public static final hun n = new hun("pref_cuttlefish_front_torch_mode_key", "off");
    public static final huk o = new huk("pref_camera_video_back_flashmode_thermally_disabled_key", (Boolean) false);
    public static final huk p = new huk("pref_camera_hdr_plus_back_flashmode_thermally_disabled_key", (Boolean) false);
    public static final huk q = new huk("pref_video_stabilization_key", (Boolean) true);
    public static final huk r = new huk("pref_video_hevc_setting_key", htt.e);
    public static final huk s = new huk("pref_video_quality_ultra_key", (Boolean) false);
    public static final huk t = new huk("pref_first_time_video_stab_edu", (Boolean) false);
    public static final huk u = new huk("pref_speech_enhance_edu_shown", (Boolean) false);
    public static final huk v = new huk("pref_speech_enhance_ever_recorded", (Boolean) false);

    static {
        new hul("pref_speech_enhance_tooltip_countdown", 3);
        new hul("pref_speech_enhance_menu_tooltip_countdown", 3);
        w = new hul("pref_video_stab_button_untouched_count", 0);
        x = new hul("pref_double_tap_launch_edu_count", 0);
        y = new huk("pref_first_time_video_stab_tooltip", (Boolean) false);
        z = new huk("key_social_share_opt_in", (Boolean) true);
        A = new huk("pref_has_set_social_share_apps", (Boolean) false);
        B = new huk("pref_has_checked_social_share", (Boolean) false);
        C = new huk("pref_has_checked_social_share_toggle", (Boolean) false);
        D = new huk("pref_has_checked_social_app_toggle", (Boolean) false);
        E = new huk("pref_has_share_successful", (Boolean) false);
        F = new huk("pref_storage_saver", (Boolean) false);
        G = new huk("pref_storage_saver_auto_disable", (Boolean) false);
        H = new huk("pref_raw_output_previous", (Boolean) false);
        I = new hun("pref_camera_resolution_previous", "full");
        J = new hul("pref_microvideo_mode_previous", 0);
        K = new huk("pref_video_hevc_previous", (Boolean) false);
        L = new huk("pref_dynamic_depth_previous", (Boolean) false);
        M = new hun("pref_video_resolution_previous", htl.RES_1080P.name());
        N = new hun("pref_video_fps_previous", htg.FPS_30.name());
        new hum("pref_last_survey_toast_timestamp", 0L);
        new hum("pref_last_photo_taken_survey_toast_timestamp", 0L);
        new hum("pref_last_photo_taken_survey_request_timestamp", 0L);
        new hum("pref_last_dual_ev_survey_toast_timestamp", 0L);
        new hum("pref_last_dual_ev_survey_request_timestamp", 0L);
        new hum("pref_last_app_startup_survey_toast_timestamp", 0L);
        new hum("pref_last_app_startup_survey_request_timestamp", 0L);
        O = new hum("pref_updated_from_version_code", 0L);
        P = new hum("pref_last_installed_version_code", 0L);
        Q = new hul("pref_update_available_chip_dismissal_times", 0);
        R = new hul("pref_last_available_update_version_code", 0);
        S = new hum("pref_last_available_update_timestamp", 0L);
        T = new hum("pref_check_hal_update_after_gca_version", 0L);
        U = new hul("pref_hal_update_attempts", 0);
        V = new hul("pref_has_seen_vertical_pano_hint", 0);
        W = new hul("pref_camera_astro", Integer.valueOf(hls.g(2)));
        X = new hul("pref_camera_swiss", Integer.valueOf(hls.c(1)));
        Y = new hul("pref_camera_lasagna_tr", Integer.valueOf(htj.LASAGNA_TR_MEDIUM.d));
        Z = new hul("pref_camera_flounder", Integer.valueOf(hls.f(1)));
        new huk("pref_has_seen_permissions_dialogs", (Boolean) false);
        aa = new hun("pref_camera_photosphere_orientation", "pano_photosphere");
        ab = new huk("pref_mars_enabled", (Boolean) false);
        ac = new hum("pref_release_dialog_last_shown_timestamp", 0L);
    }
}
