package defpackage;

import android.R;

/* JADX INFO: loaded from: classes2.dex */
public final class nxe {
    public static final int[] a = {R.attr.background, R.attr.touchscreenBlocksFocus, R.attr.keyboardNavigationCluster, com.google.android.GoogleCameraEngR18F1.R.attr.elevation, com.google.android.GoogleCameraEngR18F1.R.attr.expanded, com.google.android.GoogleCameraEngR18F1.R.attr.liftOnScroll, com.google.android.GoogleCameraEngR18F1.R.attr.liftOnScrollTargetViewId, com.google.android.GoogleCameraEngR18F1.R.attr.statusBarForeground};
    public static final int[] b = {com.google.android.GoogleCameraEngR18F1.R.attr.layout_scrollEffect, com.google.android.GoogleCameraEngR18F1.R.attr.layout_scrollFlags, com.google.android.GoogleCameraEngR18F1.R.attr.layout_scrollInterpolator};
    public static final int[] c = {com.google.android.GoogleCameraEngR18F1.R.attr.collapsedTitleGravity, com.google.android.GoogleCameraEngR18F1.R.attr.collapsedTitleTextAppearance, com.google.android.GoogleCameraEngR18F1.R.attr.collapsedTitleTextColor, com.google.android.GoogleCameraEngR18F1.R.attr.contentScrim, com.google.android.GoogleCameraEngR18F1.R.attr.expandedTitleGravity, com.google.android.GoogleCameraEngR18F1.R.attr.expandedTitleMargin, com.google.android.GoogleCameraEngR18F1.R.attr.expandedTitleMarginBottom, com.google.android.GoogleCameraEngR18F1.R.attr.expandedTitleMarginEnd, com.google.android.GoogleCameraEngR18F1.R.attr.expandedTitleMarginStart, com.google.android.GoogleCameraEngR18F1.R.attr.expandedTitleMarginTop, com.google.android.GoogleCameraEngR18F1.R.attr.expandedTitleTextAppearance, com.google.android.GoogleCameraEngR18F1.R.attr.expandedTitleTextColor, com.google.android.GoogleCameraEngR18F1.R.attr.extraMultilineHeightEnabled, com.google.android.GoogleCameraEngR18F1.R.attr.forceApplySystemWindowInsetTop, com.google.android.GoogleCameraEngR18F1.R.attr.maxLines, com.google.android.GoogleCameraEngR18F1.R.attr.scrimAnimationDuration, com.google.android.GoogleCameraEngR18F1.R.attr.scrimVisibleHeightTrigger, com.google.android.GoogleCameraEngR18F1.R.attr.statusBarScrim, com.google.android.GoogleCameraEngR18F1.R.attr.title, com.google.android.GoogleCameraEngR18F1.R.attr.titleCollapseMode, com.google.android.GoogleCameraEngR18F1.R.attr.titleEnabled, com.google.android.GoogleCameraEngR18F1.R.attr.toolbarId};
    public static final int[] d = {com.google.android.GoogleCameraEngR18F1.R.attr.layout_collapseMode, com.google.android.GoogleCameraEngR18F1.R.attr.layout_collapseParallaxMultiplier};
    public static final int[] e = {com.google.android.GoogleCameraEngR18F1.R.attr.behavior_overlapTop};
}
