package defpackage;

import java.util.Arrays;
import java.util.HashMap;

/* JADX INFO: loaded from: classes2.dex */
public final class zp {
    int a;
    public final zs b = new zs();
    public final zr c = new zr();
    public final zq d = new zq();
    public final zt e = new zt();
    public HashMap f = new HashMap();
    zo g;

    public final void a(zk zkVar) {
        zq zqVar = this.d;
        zkVar.d = zqVar.i;
        zkVar.e = zqVar.j;
        zkVar.f = zqVar.k;
        zkVar.g = zqVar.l;
        zkVar.h = zqVar.m;
        zkVar.i = zqVar.n;
        zkVar.j = zqVar.o;
        zkVar.k = zqVar.p;
        zkVar.l = zqVar.q;
        zkVar.m = zqVar.r;
        zkVar.n = zqVar.s;
        zkVar.r = zqVar.t;
        zkVar.s = zqVar.u;
        zkVar.t = zqVar.v;
        zkVar.u = zqVar.w;
        zkVar.leftMargin = zqVar.G;
        zkVar.rightMargin = this.d.H;
        zkVar.topMargin = this.d.I;
        zkVar.bottomMargin = this.d.J;
        zq zqVar2 = this.d;
        zkVar.z = zqVar2.S;
        zkVar.A = zqVar2.R;
        zkVar.w = zqVar2.O;
        zkVar.y = zqVar2.Q;
        zkVar.D = zqVar2.x;
        zkVar.E = zqVar2.y;
        zkVar.o = zqVar2.A;
        zkVar.p = zqVar2.B;
        zkVar.q = zqVar2.C;
        zkVar.F = zqVar2.z;
        zkVar.S = zqVar2.D;
        zkVar.T = zqVar2.E;
        zkVar.H = zqVar2.U;
        zkVar.G = zqVar2.V;
        zkVar.J = zqVar2.X;
        zkVar.I = zqVar2.W;
        zkVar.V = zqVar2.am;
        zkVar.W = zqVar2.an;
        zkVar.K = zqVar2.Y;
        zkVar.L = zqVar2.Z;
        zkVar.O = zqVar2.aa;
        zkVar.P = zqVar2.ab;
        zkVar.M = zqVar2.ac;
        zkVar.N = zqVar2.ad;
        zkVar.Q = zqVar2.ae;
        zkVar.R = zqVar2.af;
        zkVar.U = zqVar2.F;
        zkVar.c = zqVar2.h;
        zkVar.a = zqVar2.f;
        zkVar.b = zqVar2.g;
        zkVar.width = zqVar2.d;
        zkVar.height = this.d.e;
        zq zqVar3 = this.d;
        String str = zqVar3.al;
        if (str != null) {
            zkVar.X = str;
        }
        zkVar.Y = zqVar3.ap;
        zkVar.setMarginStart(zqVar3.L);
        zkVar.setMarginEnd(this.d.K);
        zkVar.a();
    }

    public final /* bridge */ /* synthetic */ Object clone() {
        zp zpVar = new zp();
        zq zqVar = zpVar.d;
        zq zqVar2 = this.d;
        zqVar.b = zqVar2.b;
        zqVar.d = zqVar2.d;
        zqVar.c = zqVar2.c;
        zqVar.e = zqVar2.e;
        zqVar.f = zqVar2.f;
        zqVar.g = zqVar2.g;
        zqVar.h = zqVar2.h;
        zqVar.i = zqVar2.i;
        zqVar.j = zqVar2.j;
        zqVar.k = zqVar2.k;
        zqVar.l = zqVar2.l;
        zqVar.m = zqVar2.m;
        zqVar.n = zqVar2.n;
        zqVar.o = zqVar2.o;
        zqVar.p = zqVar2.p;
        zqVar.q = zqVar2.q;
        zqVar.r = zqVar2.r;
        zqVar.s = zqVar2.s;
        zqVar.t = zqVar2.t;
        zqVar.u = zqVar2.u;
        zqVar.v = zqVar2.v;
        zqVar.w = zqVar2.w;
        zqVar.x = zqVar2.x;
        zqVar.y = zqVar2.y;
        zqVar.z = zqVar2.z;
        zqVar.A = zqVar2.A;
        zqVar.B = zqVar2.B;
        zqVar.C = zqVar2.C;
        zqVar.D = zqVar2.D;
        zqVar.E = zqVar2.E;
        zqVar.F = zqVar2.F;
        zqVar.G = zqVar2.G;
        zqVar.H = zqVar2.H;
        zqVar.I = zqVar2.I;
        zqVar.J = zqVar2.J;
        zqVar.K = zqVar2.K;
        zqVar.L = zqVar2.L;
        zqVar.M = zqVar2.M;
        zqVar.N = zqVar2.N;
        zqVar.O = zqVar2.O;
        zqVar.P = zqVar2.P;
        zqVar.Q = zqVar2.Q;
        zqVar.R = zqVar2.R;
        zqVar.S = zqVar2.S;
        zqVar.T = zqVar2.T;
        zqVar.U = zqVar2.U;
        zqVar.V = zqVar2.V;
        zqVar.W = zqVar2.W;
        zqVar.X = zqVar2.X;
        zqVar.Y = zqVar2.Y;
        zqVar.Z = zqVar2.Z;
        zqVar.aa = zqVar2.aa;
        zqVar.ab = zqVar2.ab;
        zqVar.ac = zqVar2.ac;
        zqVar.ad = zqVar2.ad;
        zqVar.ae = zqVar2.ae;
        zqVar.af = zqVar2.af;
        zqVar.ag = zqVar2.ag;
        zqVar.ah = zqVar2.ah;
        zqVar.ai = zqVar2.ai;
        zqVar.al = zqVar2.al;
        int[] iArr = zqVar2.aj;
        if (iArr != null) {
            zqVar.aj = Arrays.copyOf(iArr, iArr.length);
        } else {
            zqVar.aj = null;
        }
        zqVar.ak = zqVar2.ak;
        zqVar.am = zqVar2.am;
        zqVar.an = zqVar2.an;
        zqVar.ao = zqVar2.ao;
        zqVar.ap = zqVar2.ap;
        zr zrVar = zpVar.c;
        zr zrVar2 = this.c;
        zrVar.b = zrVar2.b;
        zrVar.c = zrVar2.c;
        zrVar.e = zrVar2.e;
        zrVar.f = zrVar2.f;
        zrVar.g = zrVar2.g;
        zrVar.j = zrVar2.j;
        zrVar.h = zrVar2.h;
        zrVar.i = zrVar2.i;
        zs zsVar = zpVar.b;
        zs zsVar2 = this.b;
        zsVar.a = zsVar2.a;
        zsVar.b = zsVar2.b;
        zsVar.d = zsVar2.d;
        zsVar.e = zsVar2.e;
        zsVar.c = zsVar2.c;
        zt ztVar = zpVar.e;
        zt ztVar2 = this.e;
        ztVar.b = ztVar2.b;
        ztVar.c = ztVar2.c;
        ztVar.d = ztVar2.d;
        ztVar.e = ztVar2.e;
        ztVar.f = ztVar2.f;
        ztVar.g = ztVar2.g;
        ztVar.h = ztVar2.h;
        ztVar.i = ztVar2.i;
        ztVar.j = ztVar2.j;
        ztVar.k = ztVar2.k;
        ztVar.l = ztVar2.l;
        ztVar.m = ztVar2.m;
        ztVar.n = ztVar2.n;
        ztVar.o = ztVar2.o;
        zpVar.a = this.a;
        zpVar.g = this.g;
        return zpVar;
    }
}
